### ISSUE TITLE
NoneType error in pseudogene

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/TBProfiler#116]
Hi Jody,

Sorry for all the questions! I got an error on running two samples. Looks like this:

set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE\t%TBCSQ\t%TGT\t%AD]\n' ./tbprofiler.targets.csq.vcf.gz
Command Failed! Please Check!Exception ignored in: <generator object cmd_out at 0x7efec4e33e50>
Traceback (most recent call last):
  File "/home/cmeehan/miniconda3/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 162, in cmd_out
    exit(1)
  File "/home/cmeehan/miniconda3/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
Traceback (most recent call last):
  File "/home/cmeehan/miniconda3/bin/tb-profiler", line 459, in <module>
    args.func(args)
  File "/home/cmeehan/miniconda3/bin/tb-profiler", line 118, in main_profile
    missing_cov_threshold=args.missing_cov_threshold
  File "/home/cmeehan/miniconda3/lib/python3.7/site-packages/pathogenprofiler/profiler.py", line 29, in bam_profiler
    csq = csq_vcf_obj.load_csq(ann_file=conf["ann"])
  File "/home/cmeehan/miniconda3/lib/python3.7/site-packages/pathogenprofiler/vcf.py", line 109, in load_csq
    if info[-1] == "pseudogene": continue
TypeError: 'NoneType' object is not subscriptable

I can't figure out what is causing it; the samples don't seem to be anything special like bad quality genome. Any idea what has happened here?

Cheers,
Conor

**Comment by jodyphelan** [comment]
Hey Conor,

I'll have a look to see if I can duplicate this in any of our samples and see what is happening.
Is it just the standard library or is it a modified one?

Jody

**Comment by jodyphelan** [comment]
I had a look and it is due to an out of date library file (with a slightly different format) in the release. I am updating with a new release now but if you run `tb-profiler update_tbdb` it should fix it without having to update everything.

**Comment by conmeehan** [comment]
That worked, thanks so much

**Comment by jodyphelan** [comment]
No problem!
