### ISSUE TITLE
Error with start_lost variant

### ISSUE THREAD

**Issue by pgcudahy** [jodyphelan/TBProfiler#139]
Hello Jody, hope you've been well. I was hoping you could help me with an error. One sample of mine is consistently failing with 
```
Running command:
set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE\t%TBCSQ\t%TGT\t%AD]\n' ./R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001.targets.csq.vcf.gz
Command Failed! Please Check!Exception ignored in: <generator object cmd_out at 0x2b5a6685a190>
Traceback (most recent call last):
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/lib/python3.8/site-packages/pathogenprofiler/utils.py", line 162, in cmd_out
    exit(1)
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
Traceback (most recent call last):
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/bin/tb-profiler", line 507, in <module>
    args.func(args)
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/bin/tb-profiler", line 113, in main_profile
    results = pp.bam_profiler(
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/lib/python3.8/site-packages/pathogenprofiler/profiler.py", line 29, in bam_profiler
    csq = csq_vcf_obj.load_csq(ann_file=conf["ann"])
  File "/gpfs/ysm/project/cohen_theodore/pgc29/conda_envs/tbprofiler/lib/python3.8/site-packages/pathogenprofiler/vcf.py", line 117, in load_csq
    variants[sample].append({"sample":sample,"gene_id":gene_id,"gene_name":gene_name,"chr":chrom,"genome_pos":pos,"type":info[0],"change":info[5],"freq":adr[call2], "nucleotide_change":info[6]})
IndexError: list index out of range
```
I think the issue is a line in the `targets.csq.vcf` file.

The error message references function `load_csq` which starts with `bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE\t%TBCSQ\t%TGT\t%AD]\n' R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001.targets.csq.vcf.gz` (pathogenprofiler/vcf.py line 58), and with my sample I get
```
['Chromosome', '7362', 'G', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|gyrA|Rv0006|protein_coding|+|21E>21Q|7362G>C', 'missense|gyrA|Rv0006|protein_coding|+|21E>21Q|7362G>C', 'C/C', '0,190']
['Chromosome', '7585', 'G', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|gyrA|Rv0006|protein_coding|+|95S>95T|7585G>C', 'missense|gyrA|Rv0006|protein_coding|+|95S>95T|7585G>C', 'C/C', '0,181']
['Chromosome', '9304', 'G', 'A', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|gyrA|Rv0006|protein_coding|+|668G>668D|9304G>A', 'missense|gyrA|Rv0006|protein_coding|+|668G>668D|9304G>A', 'A/A', '0,170']
['Chromosome', '491742', 'T', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|fgd1|Rv0407|protein_coding|+|320F|491742T>C', 'synonymous|fgd1|Rv0407|protein_coding|+|320F|491742T>C', 'C/C', '1,165']
['Chromosome', '575907', 'C', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|mshA|Rv0486|protein_coding|+|187A>187V|575907C>T', 'missense|mshA|Rv0486|protein_coding|+|187A>187V|575907C>T', 'T/T', '0,152']
['Chromosome', '760766', 'G', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|rpoB|Rv0667|protein_coding|+|320E>320D|760766G>T', 'missense|rpoB|Rv0667|protein_coding|+|320E>320D|760766G>T', 'T/T', '0,124']
['Chromosome', '761110', 'A', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|rpoB|Rv0667|protein_coding|+|435D>435V|761110A>T', 'missense|rpoB|Rv0667|protein_coding|+|435D>435V|761110A>T', 'T/T', '0,154']
['Chromosome', '763031', 'T', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|rpoB|Rv0667|protein_coding|+|1075A|763031T>C', 'synonymous|rpoB|Rv0667|protein_coding|+|1075A|763031T>C', 'C/C', '1,143']
['Chromosome', '781395', 'T', 'C']
['Chromosome', '781687', 'A', 'G', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|rpsL|Rv0682|protein_coding|+|43K>43R|781687A>G', 'missense|rpsL|Rv0682|protein_coding|+|43K>43R|781687A>G', 'G/G', '0,137']
['Chromosome', '1834177', 'A', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|rpsA|Rv1630|protein_coding|+|212R|1834177A>C', 'synonymous|rpsA|Rv1630|protein_coding|+|212R|1834177A>C', 'C/C', '0,158']
['Chromosome', '1917972', 'A', 'G', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|tlyA|Rv1694|protein_coding|+|11L|1917972A>G', 'synonymous|tlyA|Rv1694|protein_coding|+|11L|1917972A>G', 'G/G', '0,172']
['Chromosome', '2153912', 'G', 'A', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|katG|Rv1908c|protein_coding|-|734L>734F|2153912G>A', 'missense|katG|Rv1908c|protein_coding|-|734L>734F|2153912G>A', 'A/A', '2,93']
['Chromosome', '2153914', 'T', 'G', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|katG|Rv1908c|protein_coding|-|733N>733T|2153914T>G', 'missense|katG|Rv1908c|protein_coding|-|733N>733T|2153914T>G', 'G/G', '1,92']
['Chromosome', '2154724', 'C', 'A', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|katG|Rv1908c|protein_coding|-|463R>463L|2154724C>A', 'missense|katG|Rv1908c|protein_coding|-|463R>463L|2154724C>A', 'A/A', '0,139']
['Chromosome', '2289240', 'A', 'G', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'start_lost|pncA|Rv2043c|protein_coding|-', 'start_lost|pncA|Rv2043c|protein_coding|-', 'G/G', '0,149']
['Chromosome', '2726141', 'C', 'T']
['Chromosome', '3067945', 'C', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|thyX|Rv2754c|protein_coding|-|1V>1M|3067945C>T', 'missense|thyX|Rv2754c|protein_coding|-|1V>1M|3067945C>T', 'T/T', '0,179']
['Chromosome', '3086788', 'T', 'C']
['Chromosome', '3640268', 'T', 'G']
['Chromosome', '3640269', 'A', 'T']
['Chromosome', '4242643', 'C', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|embC|Rv3793|protein_coding|+|927R|4242643C>T', 'synonymous|embC|Rv3793|protein_coding|+|927R|4242643C>T', 'T/T', '0,144']
['Chromosome', '4243460', 'C', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|embA|Rv3794|protein_coding|+|76C|4243460C>T', 'synonymous|embA|Rv3794|protein_coding|+|76C|4243460C>T', 'T/T', '0,157']
['Chromosome', '4246085', 'G', 'T', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|embA|Rv3794|protein_coding|+|951E>951D|4246085G>T', 'missense|embA|Rv3794|protein_coding|+|951E>951D|4246085G>T', 'T/T', '0,107']
['Chromosome', '4407588', 'T', 'C', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'synonymous|gid|Rv3919c|protein_coding|-|205A|4407588T>C', 'synonymous|gid|Rv3919c|protein_coding|-|205A|4407588T>C', 'C/C', '0,162']
['Chromosome', '4407927', 'T', 'G', 'R10183_BSSE_QGF_150796_HTTLWDRXX_1_G45079_ACTAAGAT_AACCGCGG_S25_L001', 'missense|gid|Rv3919c|protein_coding|-|92E>92D|4407927T>G', 'missense|gid|Rv3919c|protein_coding|-|92E>92D|4407927T>G', 'G/G', '0,188']
```
You can see at position 2289240 is a `start_lost`. Later in the `load_csq()` function (pathogenprofiler/vcf.py line 116) there's 
```
elif  "missense" in info[0] or "start_lost" in info[0] or "stop_gained" in info[0]: 
 variants[sample].append({"sample":sample,"gene_id":gene_id,"gene_name":gene_name,"chr":chrom,"genome_pos":pos,"type":info[0],"change":info[5],"freq":adr[call2], "nucleotide_change":info[6]})
```
And I think the relevant `info` list for the start_lost line in the vcf would be 
```
[['start_lost', 'pncA', 'Rv2043c', 'protein_coding', '-']
```
So this variant doesn't have an info[5] of info[6], thus the `IndexError: list index out of range`.  I'm not familiar enough with the internals of your tool to suggest a change, but hopefully this helps you. If it helps, I can send you the fastq or vcf file directly. Thanks

**Comment by jodyphelan** [comment]
Thanks, all good here!

Interesting, I haven't seen that error before but it seems you've already spooted where the problem lies, should be a relatively quick fix I think. I'll see if I can replicate the error and should get that patched asap.

Jody

**Comment by jodyphelan** [comment]
This should be fixed now in the v3 release, thanks for letting me know!
