### ISSUE TITLE
After the update to tb-profiler 4.0.0, I have got this error please help me to figure it out, Thanks

### ISSUE THREAD

**Issue by Manigandan-Venkatesan** [jodyphelan/TBProfiler#185]
Error started at -
Running command:
set -u pipefail; bcftools view -v snps ./ef9ac70d-7469-47e0-bee1-9ddc08f313a6.targets.vcf.gz | combine_vcf_variants.py --ref /home/micro/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta --gff /home/micro/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.gff | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 04cb17cf-367d-4028-a604-e625e7fc9beb.vcf
Traceback (most recent call last):
  File "/home/micro/miniconda3/envs/tb-profiler/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/home/micro/miniconda3/envs/tb-profiler/bin/tb-profiler", line 171, in main_profile
    results = pp.bam_profiler(
  File "/home/micro/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/profiler.py", line 32, in bam_profiler
    ann_vcf_obj = vcf_obj.run_snpeff(conf["snpEff_db"],conf["ref"],conf["gff"],rename_chroms= conf["chromosome_conversion"])
  File "/home/micro/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/vcf.py", line 60, in run_snpeff
    run_cmd("bcftools view -v snps %(filename)s | combine_vcf_variants.py --ref %(ref_file)s --gff %(gff_file)s | %(rename_cmd)s snpEff ann -noStats %(db)s - %(re_rename_cmd)s > %(tmp_file1)s" % vars(self))
  File "/home/micro/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 255, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; bcftools view -v snps ./ef9ac70d-7469-47e0-bee1-9ddc08f313a6.targets.vcf.gz | combine_vcf_variants.py --ref /home/micro/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta --gff /home/micro/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.gff | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 04cb17cf-367d-4028-a604-e625e7fc9beb.vcf
stderr:
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 1: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 2: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 3: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 6: Syntax error: "(" unexpected
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 1: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 2: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 3: import: not found
/home/micro/miniconda3/envs/tb-profiler/bin/rename_vcf_chrom.py: 6: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/micro/miniconda3/envs/tb-profiler/bin/combine_vcf_variants.py", line 82, in <module>
    args.func(args)
  File "/home/micro/miniconda3/envs/tb-profiler/bin/combine_vcf_variants.py", line 74, in main
    sys.stdout.write("\t".join(row)+"\n")
BrokenPipeError: [Errno 32] Broken pipe
java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
	at org.snpeff.util.Download.unzip(Download.java:296)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:33)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1221)
	at org.snpeff.SnpEff.loadDb(SnpEff.java:515)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1001)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at org.snpeff.util.Download.unzip(Download.java:275)
	... 9 more
java.lang.RuntimeException: Genome download failed!
	at org.snpeff.SnpEff.loadDb(SnpEff.java:516)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1001)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)

Cleaning up after failed run

**Comment by jodyphelan** [comment]
Hi @Manigandan-Venkatesan 

Thanks for reporting this. There was a bug introduced in the v4.0.0 release which has now been fixed. Please upgrade to v4.0.1 and let me know if this fixes the issue.

**Comment by jodyphelan** [comment]
Closing this issue, feel free to re-open if still getting this error
