### ISSUE TITLE
tb-profiler update_tbdb produces error

### ISSUE THREAD

**Issue by ponomarevsy** [jodyphelan/TBProfiler#186]
I am getting this error: "FileNotFoundError: [Errno 2] No such file or directory: 'variables.json'" in version 4+ of tb-profiler when running "tb-profiler update_tbdb". This seems new, - I don't remember anything like that happening in older versions. 

```
» tb-profiler update_tbdb

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db
Traceback (most recent call last):
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/bin/tb-profiler", line 231, in main_update_tbdb
    pp.run_cmd("tb-profiler create_db %s" % tmp)
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/lib/python3.6/site-packages/pathogenprofiler/utils.py", line 255, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db
stderr:
Traceback (most recent call last):
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/bin/tb-profiler", line 237, in main_create_db
    tbp.create_db(args)
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/lib/python3.6/site-packages/tbprofiler/db.py", line 401, in create_db
    mutation_lookup = get_snpeff_formated_mutation_list(args.csv,"genome.fasta","genome.gff",json.load(open("variables.json"))["snpEff_db"])
FileNotFoundError: [Errno 2] No such file or directory: 'variables.json'


################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (tbdb.errlog)

###############################################################################


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/path/Anaconda3/2020.07/envs/tbprofiler-4.0.0-python3/bin/tb-profiler", line 30, in cleanup
    with open(outfile, "w") as O:
UnboundLocalError: local variable 'outfile' referenced before assignment
```

Please advice on how to proceed. Thank you!

**Comment by jodyphelan** [comment]
Hi @ponomarevsy,

This is related to a new format introduced in the recent TB-Profiler update. Could you try again? I've now updated the format on tbdb too. Also I see you are running tb-profiler v4.0.0, there was a small bug in this release so it would be best to upgrade to v4.0.2.

Let me know if that works for you.

**Comment by ponomarevsy** [comment]
Thank you for the fast response, @jodyphelan, - this time it ran without any issues:

» tb-profiler update_tbdb

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db

Running command:
set -u pipefail; tb-profiler load_library tbdb
Sucessfully updated TBDB 

I've, also, updated tn-profiler to v4.0.2 following your suggestion. Case closed!

**Comment by jodyphelan** [comment]
Great news!
