### ISSUE TITLE
bioconda: additional packages needed for PDF output

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#195]
On my Ubuntu 20.04 I also needed to install these additional packages from conda when setting PDF output in TBProfiler 4.0.3 using argument `--pdf`:
```
jinja2
weasyprint=52.5
```

Maybe it's worth adding them to the bioconda recipe.

NB: weasyprint 53.0 was not working, it caused this error:
```
[...]
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/PIL/Image.py", line 453, in _getencoder
    encoder = getattr(core, encoder_name + "_encoder")
AttributeError: module 'PIL._imaging' has no attribute 'jpeg2k_encoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/tb403new/bin/tb-profiler", line 582, in <module>
    args.func(args)
  File "/opt/conda/miniconda3/envs/tb403new/bin/tb-profiler", line 203, in main_profile
    tbp.write_pdf(results,conf,pdf_output)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/tbprofiler/pdf.py", line 260, in write_pdf
    HTML(string=html_out).write_pdf(outfile,stylesheets=[CSS(string=css_text)])
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/__init__.py", line 180, in write_pdf
    self.render(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/document.py", line 1160, in write_pdf
    page.paint(stream, scale=scale)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/document.py", line 769, in paint
    draw_page(self._page_box, stream)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 69, in draw_page
    draw_stacking_context(stream, stacking_context)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 182, in draw_stacking_context
    draw_stacking_context(stream, child_context)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 177, in draw_stacking_context
    draw_inline_level(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 960, in draw_inline_level
    draw_inline_level(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 964, in draw_inline_level
    draw_replacedbox(stream, box)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/draw.py", line 927, in draw_replacedbox
    box.replacement.draw(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/images.py", line 56, in draw
    image_name = stream.add_image(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/document.py", line 311, in add_image
    alpha_file = self._save_jpeg2000(alpha, optimize)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/weasyprint/document.py", line 263, in _save_jpeg2000
    pillow_image.save(
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/PIL/Jpeg2KImagePlugin.py", line 346, in _save
    ImageFile._save(im, fp, [("jpeg2k", (0, 0) + im.size, 0, kind)])
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/PIL/ImageFile.py", line 509, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/opt/conda/miniconda3/envs/tb403new/lib/python3.9/site-packages/PIL/Image.py", line 455, in _getencoder
    raise OSError(f"encoder {encoder_name} not available") from e
OSError: encoder jpeg2k not available
```

**Comment by jodyphelan** [comment]
Thanks, I'll add them into the recipe!
