### ISSUE TITLE
fasta_profile not working for certain genomes

### ISSUE THREAD

**Issue by 0xaf1f** [jodyphelan/TBProfiler#208]
I just created a conda envionment, installed tb-profiler (4.1.1), and tried to process a bunch of genomes, but many of them failed a certain way. With CDC1551, for example:

```
$ tb-profiler fasta_profile --txt --fasta  ../../genomes/CDC1551.fasta --prefix CDC1551
Using gff file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.gff
Using ref file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.fasta
Using barcode file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.bed
Using json_db file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.dr.json
Using version file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.version.json
Using variables file: /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.variables.json

Running command:
set -u pipefail; minimap2 /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.fasta ../../genomes/CDC1551.fasta --cs | sort -k6,6 -k8,8n | paftools.js call -l 100 -L 100 -f /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.fasta -s CDC1551 - | add_dummy_AD.py | bcftools view -Oz -o CDC1551.vcf.gz

Running command:
set -u pipefail; bcftools index --threads 1 -ft CDC1551.vcf.gz

Running command:
set -u pipefail; bcftools query -l CDC1551.vcf.gz

Running command:
set -u pipefail; bcftools view -c 1 CDC1551.vcf.gz -Oz -o CDC1551.targets.vcf.gz -T /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.bed

Running command:
set -u pipefail; bcftools view -v snps CDC1551.vcf.gz | combine_vcf_variants.py --ref /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.fasta --gff /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.gff | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noLog -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 80c93892-886b-46ab-87dc-d5d1d83c243d.vcf

Running command:
set -u pipefail; bcftools view -v indels CDC1551.vcf.gz | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noLog -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 63bf0a57-3743-40b2-bfe2-b97c89f265cd.vcf

Running command:
set -u pipefail; bcftools concat 80c93892-886b-46ab-87dc-d5d1d83c243d.vcf 63bf0a57-3743-40b2-bfe2-b97c89f265cd.vcf | bcftools sort -Oz -o CDC1551.csq.vcf.gz
Removing 80c93892-886b-46ab-87dc-d5d1d83c243d.vcf
Removing 63bf0a57-3743-40b2-bfe2-b97c89f265cd.vcf

Running command:
set -u pipefail; bcftools index --threads 1 -ft CDC1551.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -l CDC1551.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT\t%ANN\t[%AD]\n' CDC1551.csq.vcf.gz

Running command:
set -u pipefail; bcftools convert --gvcf2vcf -f /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.fasta CDC1551.csq.vcf.gz  | bcftools view -T /path/to/conda/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed  | bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT\t%AD]\n'

Running command:
set -u pipefail; rm CDC1551.vcf.gz
Traceback (most recent call last):
  File "/path/to/conda/envs/tb-profiler/bin/tb-profiler", line 616, in <module>
    args.func(args)
  File "/path/to/conda/envs/tb-profiler/bin/tb-profiler", line 362, in main_fasta_profile
    tbp.write_text(results,conf,text_output,extra_columns,reporting_af=0.7)
  File "/path/to/conda/envs/tb-profiler/lib/python3.9/site-packages/tbprofiler/text.py", line 127, in write_text
    text_strings["med_dp"] = json_results["qc"]["median_coverage"]
KeyError: 'median_coverage'

```

**Comment by jodyphelan** [comment]
Hi @0xaf1f ,

Thanks this looks like a bug. I'll look into it and get it fixed asap.

**Comment by 0xaf1f** [comment]
If I remove the `--txt` flag, it seems to be fine.

**Comment by jodyphelan** [comment]
Ok this should be fixed in the latest version. I'll release a conda update soon
