### ISSUE TITLE
tb-profiler update_tbdb problem

### ISSUE THREAD

**Issue by Kevi84LA** [jodyphelan/TBProfiler#214]
Hello jody,
i installed tb-profiler manually with all dependancies. When we want to update with the commande tb-profiler update_tbdb, i have the following issue.

tb-profiler update_tbdb

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db --seqname Chromosome
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 584, in <module>
    args.func(args)
  File "/home/kevinla/.local/bin/tb-profiler", line 226, in main_update_tbdb
    pp.run_cmd("tb-profiler create_db --seqname %s" % args.seqname)
  File "/home/kevinla/.local/lib/python3.6/site-packages/pathogenprofiler/utils.py", line 242, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db --seqname Chromosome
stderr:
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 584, in <module>
    args.func(args)
  File "/home/kevinla/.local/bin/tb-profiler", line 232, in main_create_db
    tbp.create_db(args)
  File "/home/kevinla/.local/lib/python3.6/site-packages/tbprofiler/db.py", line 194, in create_db
    gene_info = load_gene_info("genes.txt")
  File "/home/kevinla/.local/lib/python3.6/site-packages/tbprofiler/db.py", line 183, in load_gene_info
    for l in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'genes.txt'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 34, in cleanup
    O.write("* Database version: %s\n" % json.load(open(conf["version"]))["commit"])
TypeError: 'NoneType' object is not subscriptable

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 30, in cleanup
    with open(outfile, "w") as O:
UnboundLocalError: local variable 'outfile' referenced before assignment

**Comment by jodyphelan** [comment]
Hi @Kevi84LA 

I think it might be an old version of tb-profiler. Can you run `tb-profiler version` and paste the output here?

**Comment by Kevi84LA** [comment]
Thanks ! I have the tb-profiler 3.0.8. 
I update it, and now i have the following prompt.
./tb-profiler update_tbdb

Running command:
set -u pipefail; git clone https://github.com/jodyphelan/tbdb.git

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db 
Traceback (most recent call last):
  File "./tb-profiler", line 616, in <module>
    args.func(args)
  File "./tb-profiler", line 259, in main_update_tbdb
    pp.run_cmd("tb-profiler create_db %s" % tmp)
  File "/home/kevinla/bin/TBProfiler-4.1.1/pathogenprofiler/utils.py", line 277, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db 
stderr:
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 584, in <module>
    args.func(args)
  File "/home/kevinla/.local/bin/tb-profiler", line 232, in main_create_db
    tbp.create_db(args)
  File "/home/kevinla/.local/lib/python3.6/site-packages/tbprofiler/db.py", line 194, in create_db
    gene_info = load_gene_info("genes.txt")
  File "/home/kevinla/.local/lib/python3.6/site-packages/tbprofiler/db.py", line 183, in load_gene_info
    for l in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'genes.txt'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/kevinla/.local/bin/tb-profiler", line 34, in cleanup
    O.write("* Database version: %s\n" % json.load(open(conf["version"]))["commit"])
TypeError: 'NoneType' object is not subscriptable

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./tb-profiler", line 31, in cleanup
    with open(outfile, "w") as O:
UnboundLocalError: local variable 'outfile' referenced before assignment

**Comment by jodyphelan** [comment]
It looks like it might still be not the latest release did you download from the latest release? https://github.com/jodyphelan/TBProfiler/releases/tag/v4.1.1

**Comment by Kevi84LA** [comment]
Yes this is the prompt of my terminal when i type this command : ./tb-profiler --version
TBProfiler version 4.1.1

**Comment by jodyphelan** [comment]
Hi @Kevi84LA,

`tb-profiler` has now been updated. could you try again with the latest version?
