### ISSUE TITLE
samtools command failed - fixmate: invalid option -- '@'

### ISSUE THREAD

**Issue by aset8** [jodyphelan/TBProfiler#218]
Tried different options to start the program. One of them:

`path/tb-profiler profile --platform illumina --read1 /path/163_S2_L001_R1_001.fastq.gz --read2 /path/163_S2_L001_R2_001.fastq.gz --prefix 163_S2`

Output:
```
Using ref file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.fasta
Using gff file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.gff
Using bed file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.bed
Using version file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.version.json
Using json_db file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.dr.json
Using variables file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.variables.json
Using spoligotype_spacers file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.spoligotype_spacers.txt
Using barcode file: /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.barcode.bed

Running command:
set -u pipefail; trimmomatic PE -threads 1 -phred33 /path/163_S2_L001_R1_001.fastq.gz /path/163_S2_L001_R2_001.fastq.gz -baseout ./bb172e5e-9b07-42c5-8ab9-8033faea3091 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36

Running command:
set -u pipefail; cat ./bb172e5e-9b07-42c5-8ab9-8033faea3091_1U ./bb172e5e-9b07-42c5-8ab9-8033faea3091_2U > ./bb172e5e-9b07-42c5-8ab9-8033faea3091_TU

Running command:
set -u pipefail; rm ./bb172e5e-9b07-42c5-8ab9-8033faea3091_1U ./bb172e5e-9b07-42c5-8ab9-8033faea3091_2U

Running command:
set -u pipefail; bwa mem -t 1 -K 10000000 -c 100 -R '@RG\tID:163_S2\tSM:163_S2\tPL:illumina' -M -T 50 /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.fasta ./bb172e5e-9b07-42c5-8ab9-8033faea3091_1P ./bb172e5e-9b07-42c5-8ab9-8033faea3091_2P | samtools sort -@ 1 -o ./bb172e5e-9b07-42c5-8ab9-8033faea3091.pair.bam -

Running command:
set -u pipefail; bwa mem -t 1 -K 10000000 -c 100 -R '@RG\tID:163_S2\tSM:163_S2\tPL:illumina' -M -T 50 /home/adminrig/miniconda3/envs/tb/share/tbprofiler//tbdb.fasta ./bb172e5e-9b07-42c5-8ab9-8033faea3091_TU | samtools sort -@ 1 -o ./bb172e5e-9b07-42c5-8ab9-8033faea3091.single.bam -

Running command:
set -u pipefail; samtools merge -@ 1 -f ./bb172e5e-9b07-42c5-8ab9-8033faea3091.unsort.bam ./bb172e5e-9b07-42c5-8ab9-8033faea3091.pair.bam ./bb172e5e-9b07-42c5-8ab9-8033faea3091.single.bam

Running command:
set -u pipefail; samtools sort -m 768M -n -@ 1  ./bb172e5e-9b07-42c5-8ab9-8033faea3091.unsort.bam | samtools fixmate -@ 1 -m - - | samtools sort -m 768M -@ 1 - | samtools markdup -@ 1 - ./bb172e5e-9b07-42c5-8ab9-8033faea3091.bam
Traceback (most recent call last):
  File "/path/TBProfiler-4.2.0/tb-profiler", line 566, in <module>
    args.func(args)
  File "/path/TBProfiler-4.2.0/tb-profiler", line 150, in main_profile
    results.update(pp.run_profiler(args))
  File "/home/adminrig/miniconda3/envs/tb/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 36, in run_profiler
    args.bam_file = get_bam_file(args)
  File "/home/adminrig/miniconda3/envs/tb/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 110, in get_bam_file
    bam_obj = fastq_obj.map_to_ref(
  File "/home/adminrig/miniconda3/envs/tb/lib/python3.9/site-packages/pathogenprofiler/fastq.py", line 108, in map_to_ref
    run_cmd("samtools sort -m %(max_mem)s -n -@ %(threads)s  %(bam_unsort_file)s | samtools fixmate -@ %(threads)s -m - - | samtools sort -m %(max_mem)s -@ %(threads)s - | samtools markdup -@ %(threads)s - %(bam_file)s" % vars(self))
  File "/home/adminrig/miniconda3/envs/tb/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 397, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; samtools sort -m 768M -n -@ 1  ./bb172e5e-9b07-42c5-8ab9-8033faea3091.unsort.bam | samtools fixmate -@ 1 -m - - | samtools sort -m 768M -@ 1 - | samtools markdup -@ 1 - ./bb172e5e-9b07-42c5-8ab9-8033faea3091.bam
stderr:
**fixmate: invalid option -- '@'**
Usage: samtools fixmate <in.nameSrt.bam> <out.nameSrt.bam>
Options:
  -r           Remove unmapped reads and secondary alignments
  -p           Disable FR proper pair check
  -c           Add template cigar ct tag
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]

As elsewhere in samtools, use '-' as the filename for stdin/stdout. The input
file must be grouped by read name (e.g. sorted by name). Coordinated sorted
input is not accepted.
**[main] unrecognized command 'markdup'**
[bam_sort_core] merging from 2 files...

Cleaning up after failed run


################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (163_S2.errlog)

###############################################################################
```

**Comment by jodyphelan** [comment]
Hi @aset8 ,

Which version of samtools do you have installed?

**Comment by aset8** [comment]
> Hi @aset8 ,
> 
> Which version of samtools do you have installed?

Yes, it was the samtools version
updated to version 1.9, no error
Thank you!
