### ISSUE TITLE
ValueError: Cant find programs: trimmomatic

### ISSUE THREAD

**Issue by limengfdu** [jodyphelan/TBProfiler#242]
Hi Jody,
I used "mamba create -n tb-profiler tb-profiler" to install tb-profiler v4.3.0.
I ran "tb-profiler profile -1 SJ_2012_0029_R1.fastq.gz -2 SJ_2012_0029_R2.fastq.gz  -p SJ_2012_0029", and I got 

Traceback (most recent call last):
  File "/home/ferdon/miniconda3/envs/tb-profiler/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/home/ferdon/miniconda3/envs/tb-profiler/bin/tb-profiler", line 150, in main_profile
    results.update(pp.run_profiler(args))
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 36, in run_profiler
    args.bam_file = get_bam_file(args)
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 100, in get_bam_file
    fastq_obj = untrimmed_fastq_obj.trim(args.files_prefix,threads=args.threads)
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/fastq.py", line 39, in trim
    run_cmd("trimmomatic PE -threads %(threads)s -phred33 %(r1)s %(r2)s -baseout %(prefix)s LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36" % vars(self))
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 387, in run_cmd
    raise ValueError("Cant find programs: %s\n" % (", ".join(missing)))
ValueError: Cant find programs: trimmomatic

Cleaning up after failed run

How can I solve this problem?

**Comment by jodyphelan** [comment]
It looks like mamba didn't install trimmomatic for some reason. Could you post the output of the command below?
```
mamba create -n tb-profiler tb-profiler=4.3.0
```

**Comment by limengfdu** [comment]
Hi Jody,
It still did not work. Here is the output.

WARNING: A conda environment already exists at '/home/lm/miniconda3/envs/tb-profiler'
Remove existing environment (y/[n])? y


Looking for: ['tb-profiler=4.3.0']

pkgs/main/linux-64                                            No change
bioconda/linux-64                                             No change
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pk..            No change
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cl..  0.7s
bioconda/noarch                                     2.1s
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cl..            No change
pkgs/main/noarch                                  
pkgs/r/noarch                                                 No change
pkgs/r/linux-64                                               No change
conda-forge/noarch                                  3.4s
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pk..            No change
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cl..  2.4s
conda-forge/linux-64                                7.7s
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cl.. 16.7s
Transaction

  Prefix: /home/lm/miniconda3/envs/tb-profiler

  Updating specs:

   - tb-profiler=4.3.0


  Package                           Version  Build                Channel                    Size
───────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                       0.1  conda_forge          conda-forge/linux-64     Cached
  + _openmp_mutex                       4.5  2_gnu                conda-forge/linux-64     Cached
  + alsa-lib                        1.2.6.1  h7f98852_0           conda-forge/linux-64     Cached
  + bc                               1.07.1  h7f98852_0           conda-forge/linux-64     Cached
  + bcftools                           1.12  h45bccc9_1           bioconda/linux-64        Cached
  + bedtools                         2.30.0  h468198e_3           bioconda/linux-64        Cached
  + boost-cpp                        1.74.0  h75c5d50_8           conda-forge/linux-64     Cached
  + brotli                            1.0.9  h166bdaf_7           conda-forge/linux-64     Cached
  + brotli-bin                        1.0.9  h166bdaf_7           conda-forge/linux-64     Cached
  + brotlipy                          0.7.0  py39hb9d737c_1004    conda-forge/linux-64     Cached
  + bwa                              0.7.17  h7132678_9           bioconda/linux-64        Cached
  + bzip2                             1.0.8  h7f98852_4           conda-forge/linux-64     Cached
  + c-ares                           1.18.1  h7f98852_0           conda-forge/linux-64     Cached
  + ca-certificates               2022.9.14  ha878542_0           conda-forge/linux-64     Cached
  + cairo                            1.16.0  ha61ee94_1013        conda-forge/linux-64     Cached
  + certifi                       2022.9.14  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + cffi                             1.15.1  py39he91dace_0       conda-forge/linux-64     Cached
  + charset-normalizer                2.1.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + colorama                          0.4.5  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + cryptography                     37.0.4  py39hd97740a_0       conda-forge/linux-64     Cached
  + cssselect2                        0.2.1  pyh9f0ad1d_1         conda-forge/noarch       Cached
  + curl                             7.83.1  h7bff187_0           conda-forge/linux-64     Cached
  + delly                             0.8.7  he03298f_1           bioconda/linux-64        Cached
  + expat                             2.4.8  h27087fc_0           conda-forge/linux-64     Cached
  + font-ttf-dejavu-sans-mono          2.37  hab24e00_0           conda-forge/noarch       Cached
  + font-ttf-inconsolata              3.000  h77eed37_0           conda-forge/noarch       Cached
  + font-ttf-source-code-pro          2.038  h77eed37_0           conda-forge/noarch       Cached
  + font-ttf-ubuntu                    0.83  hab24e00_0           conda-forge/noarch       Cached
  + fontconfig                       2.14.0  hc2a2eb6_1           conda-forge/linux-64     Cached
  + fonts-conda-ecosystem                 1  0                    conda-forge/noarch       Cached
  + fonts-conda-forge                     1  0                    conda-forge/noarch       Cached
  + fonttools                        4.37.2  py39hb9d737c_0       conda-forge/linux-64     Cached
  + freebayes                         1.3.5  py39hba5d119_3       bioconda/linux-64        Cached
  + freetype                         2.12.1  hca18f0e_0           conda-forge/linux-64     Cached
  + fribidi                          1.0.10  h36c2ea0_0           conda-forge/linux-64     Cached
  + gatk4                           4.2.6.1  py36hdfd78af_1       bioconda/noarch          Cached
  + gettext                        0.19.8.1  h73d1719_1008        conda-forge/linux-64     Cached
  + giflib                            5.2.1  h36c2ea0_2           conda-forge/linux-64     Cached
  + git                              2.37.3  pl5321h36853c3_0     conda-forge/linux-64     Cached
  + glib                             2.72.1  h6239696_0           conda-forge/linux-64     Cached
  + glib-tools                       2.72.1  h6239696_0           conda-forge/linux-64     Cached
  + graphite2                        1.3.13  h58526e2_1001        conda-forge/linux-64     Cached
  + gsl                                 2.6  he838d99_2           conda-forge/linux-64     Cached
  + harfbuzz                          5.2.0  hf9f4e7c_0           conda-forge/linux-64     Cached
  + html5lib                            1.1  pyh9f0ad1d_0         conda-forge/noarch       Cached
  + htslib                             1.12  h9093b5e_1           bioconda/linux-64        Cached
  + icu                                70.1  h27087fc_0           conda-forge/linux-64     Cached
  + idna                                3.3  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + jbig                                2.1  h7f98852_2003        conda-forge/linux-64     Cached
  + jinja2                            3.1.2  pyhd8ed1ab_1         conda-forge/noarch       Cached
  + jpeg                                 9e  h166bdaf_2           conda-forge/linux-64     Cached
  + k8                                0.2.5  hd03093a_2           bioconda/linux-64        Cached
  + keyutils                          1.6.1  h166bdaf_0           conda-forge/linux-64     Cached
  + kmc                               3.2.1  hf1761c0_2           bioconda/linux-64        Cached
  + krb5                             1.19.3  h3790be6_0           conda-forge/linux-64     Cached
  + lcms2                              2.12  hddcbb42_0           conda-forge/linux-64     Cached
  + ld_impl_linux-64                 2.36.1  hea4e1c9_2           conda-forge/linux-64     Cached
  + lerc                              2.2.1  h9c3ff4c_0           conda-forge/linux-64     Cached
  + libblas                           3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libbrotlicommon                   1.0.9  h166bdaf_7           conda-forge/linux-64     Cached
  + libbrotlidec                      1.0.9  h166bdaf_7           conda-forge/linux-64     Cached
  + libbrotlienc                      1.0.9  h166bdaf_7           conda-forge/linux-64     Cached
  + libcblas                          3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libcups                           2.3.3  h3e49a29_2           conda-forge/linux-64     Cached
  + libcurl                          7.83.1  h7bff187_0           conda-forge/linux-64     Cached
  + libdeflate                          1.7  h7f98852_5           conda-forge/linux-64     Cached
  + libedit                    3.1.20191231  he28a2e2_2           conda-forge/linux-64     Cached
  + libev                              4.33  h516909a_1           conda-forge/linux-64     Cached
  + libffi                            3.4.2  h7f98852_5           conda-forge/linux-64     Cached
  + libgcc-ng                        12.1.0  h8d9b700_16          conda-forge/linux-64     Cached
  + libgfortran-ng                   12.1.0  h69a702a_16          conda-forge/linux-64     Cached
  + libgfortran5                     12.1.0  hdcd56e2_16          conda-forge/linux-64     Cached
  + libglib                          2.72.1  h2d90d5f_0           conda-forge/linux-64     Cached
  + libgomp                          12.1.0  h8d9b700_16          conda-forge/linux-64     Cached
  + libiconv                           1.16  h516909a_0           conda-forge/linux-64     Cached
  + libnghttp2                       1.47.0  hdcd2b5c_1           conda-forge/linux-64     Cached
  + libnsl                            2.0.0  h7f98852_0           conda-forge/linux-64     Cached
  + libopenblas                      0.3.21  pthreads_h78a6416_3  conda-forge/linux-64     Cached
  + libpng                           1.6.38  h753d276_0           conda-forge/linux-64     Cached
  + libssh2                          1.10.0  haa6b8db_3           conda-forge/linux-64     Cached
  + libstdcxx-ng                     12.1.0  ha89aaad_16          conda-forge/linux-64     Cached
  + libtiff                           4.3.0  hf544144_1           conda-forge/linux-64     Cached
  + libuuid                          2.32.1  h7f98852_1000        conda-forge/linux-64     Cached
  + libwebp                           1.2.2  h3452ae3_0           conda-forge/linux-64     Cached
  + libwebp-base                      1.2.2  h7f98852_1           conda-forge/linux-64     Cached
  + libxcb                             1.13  h7f98852_1004        conda-forge/linux-64     Cached
  + libzlib                          1.2.12  h166bdaf_3           conda-forge/linux-64     Cached
  + lofreq                            2.1.5  py39h2dde2f4_4       bioconda/linux-64        Cached
  + markupsafe                        2.1.1  py39hb9d737c_1       conda-forge/linux-64     Cached
  + minimap2                           2.24  h7132678_1           bioconda/linux-64        Cached
  + munkres                           1.1.4  pyh9f0ad1d_0         conda-forge/noarch       Cached
  + ncurses                             6.2  h58526e2_4           conda-forge/linux-64     Cached
  + openjdk                         11.0.15  h1e1ecb3_1           conda-forge/linux-64     Cached
  + openjpeg                          2.4.0  hb52868f_1           conda-forge/linux-64     Cached
  + openssl                          1.1.1q  h166bdaf_0           conda-forge/linux-64     Cached
  + pango                           1.50.10  hc4f8a73_0           conda-forge/linux-64     Cached
  + parallel                       20220722  ha770c72_0           conda-forge/linux-64     Cached
  + pathogen-profiler                 2.0.1  pypyh5e36f6f_0       bioconda/noarch          Cached
  + pcre                               8.45  h9c3ff4c_0           conda-forge/linux-64     Cached
  + pcre2                             10.37  hc3806b6_1           conda-forge/linux-64     Cached
  + perl                             5.32.1  2_h7f98852_perl5     conda-forge/linux-64     Cached
  + pillow                            9.1.1  py39hae2aec6_1       conda-forge/linux-64     Cached
  + pilon                              1.24  hdfd78af_0           bioconda/noarch          Cached
  + pip                              22.2.2  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pixman                           0.40.0  h36c2ea0_0           conda-forge/linux-64     Cached
  + pthread-stubs                       0.4  h36c2ea0_1001        conda-forge/linux-64     Cached
  + pycparser                          2.21  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pydyf                             0.2.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pyopenssl                        22.0.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pyphen                           0.13.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + pysocks                           1.7.1  pyha2e5f31_6         conda-forge/noarch       Cached
  + python                            3.9.9  h62f1059_0_cpython   conda-forge/linux-64     Cached
  + python_abi                          3.9  2_cp39               conda-forge/linux-64     Cached
  + readline                            8.1  h46c0cb4_0           conda-forge/linux-64     Cached
  + requests                         2.28.1  pyhd8ed1ab_1         conda-forge/noarch       Cached
  + samclip                           0.4.0  hdfd78af_1           bioconda/noarch          Cached
  + samtools                           1.12  h9aed4be_1           bioconda/linux-64        Cached
  + setuptools                       65.3.0  pyhd8ed1ab_1         conda-forge/noarch       Cached
  + six                              1.16.0  pyh6c4a22f_0         conda-forge/noarch       Cached
  + snpeff                              5.0  hdfd78af_1           bioconda/noarch          Cached
  + sqlite                           3.37.0  h9cd32fc_0           conda-forge/linux-64     Cached
  + tabixpp                           1.1.0  he28291e_6           bioconda/linux-64        Cached
  + tb-profiler                       4.3.0  pypyh5e36f6f_0       bioconda/noarch          Cached
  + tinycss2                          1.1.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + tk                               8.6.12  h27826a3_0           conda-forge/linux-64     Cached
  + tqdm                             4.64.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + trimmomatic                        0.39  hdfd78af_2           bioconda/noarch          Cached
  + tzdata                            2022c  h191b570_0           conda-forge/noarch       Cached
  + unicodedata2                     14.0.0  py39hb9d737c_1       conda-forge/linux-64     Cached
  + urllib3                         1.26.11  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + vcflib                            1.0.2  h3198e80_5           bioconda/linux-64        Cached
  + weasyprint                         56.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + webencodings                      0.5.1  py_1                 conda-forge/noarch       Cached
  + wheel                            0.37.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + xorg-fixesproto                     5.0  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-inputproto                   2.3.2  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-kbproto                      1.0.7  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-libice                      1.0.10  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libsm                        1.2.3  hd9c2040_1000        conda-forge/linux-64     Cached
  + xorg-libx11                       1.7.2  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libxau                       1.0.9  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libxdmcp                     1.1.3  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libxext                      1.3.4  h7f98852_1           conda-forge/linux-64     Cached
  + xorg-libxfixes                    5.0.3  h7f98852_1004        conda-forge/linux-64     Cached
  + xorg-libxi                       1.7.10  h7f98852_0           conda-forge/linux-64     Cached
  + xorg-libxrender                  0.9.10  h7f98852_1003        conda-forge/linux-64     Cached
  + xorg-libxtst                      1.2.3  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-recordproto                 1.14.2  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-renderproto                 0.11.1  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-xextproto                    7.3.0  h7f98852_1002        conda-forge/linux-64     Cached
  + xorg-xproto                      7.0.31  h7f98852_1007        conda-forge/linux-64     Cached
  + xz                                5.2.6  h166bdaf_0           conda-forge/linux-64     Cached
  + zlib                             1.2.12  h166bdaf_3           conda-forge/linux-64     Cached
  + zstd                              1.5.2  h6239696_4           conda-forge/linux-64     Cached

  Summary:

  Install: 154 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate tb-profiler

To deactivate an active environment, use

     $ mamba deactivate

**Comment by limengfdu** [comment]
Thanks for your quick reply. I reinstalled the tb-profiler v4.3.0. It failed at this step.

Running command:
set -u pipefail; samtools index -@ 4 ./29902c5f-0155-4cd1-8877-12d2f0af51dc.bam
Using ./29902c5f-0155-4cd1-8877-12d2f0af51dc.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.
Traceback (most recent call last):
  File "/home/ferdon/miniconda3/envs/tb-profiler/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/home/ferdon/miniconda3/envs/tb-profiler/bin/tb-profiler", line 150, in main_profile
    results.update(pp.run_profiler(args))
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 37, in run_profiler
    results = bam_profiler(
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/profiler.py", line 28, in bam_profiler
    vcf_obj = bam_obj.call_variants(conf["ref"], caller=caller, bed_file=conf["bed"], threads=threads, calling_params=calling_params, samclip = samclip, min_dp=min_depth)
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/bam.py", line 78, in call_variants
    run_cmd('%(windows_cmd)s | parallel -j %(threads)s --col-sep " " "%(calling_cmd)s"' % vars(self))
  File "/home/ferdon/miniconda3/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 387, in run_cmd
    raise ValueError("Cant find programs: %s\n" % (", ".join(missing)))
ValueError: Cant find programs: samclip, freebayes

which samclip
/home/ferdon/miniconda3/envs/tb-profiler/bin/samclip
which freebayes
/home/ferdon/miniconda3/envs/tb-profiler/bin/freebayes
