### ISSUE TITLE
Some samples fail using version 4.4.0 

### ISSUE THREAD

**Issue by ChiehYin** [jodyphelan/TBProfiler#252]
Hi Jody, 

I ran TBprofiler using the version 4.4.0. However, I found several samples failed but could work in previous version. 
The error log are similar. Below is one of them as example. 

Besides, can the results of .json from different version being executed `collate `together? 
Thank you!

===========================
# tb-profiler error report

* OS: linux
* Program version: 4.4.0
* Database version: c2fb9a2
* Program call:
```
{'read1': 'K192399_S128_R1.fastq.gz', 'read2': 'K192399_S128_R2.fastq.gz', 'bam': None, 'fasta': None, 'vcf': None, 'platform': 'illumina', 'db': 'tbdb', 'external_db': None, 'prefix': 'K192399_S128', 'csv': False, 'txt': False, 'pdf': False, 'output_template': None, 'add_columns': None, 'add_mutation_metadata': False, 'dir': '.', 'mapper': 'bwa', 'caller': 'freebayes', 'calling_params': None, 'min_depth': 10, 'af': 0.1, 'reporting_af': 0.1, 'coverage_fraction_threshold': 0, 'missing_cov_threshold': 10, 'suspect': False, 'spoligotype': False, 'call_whole_genome': False, 'snp_dist': None, 'no_trim': False, 'no_flagstat': False, 'no_clip': True, 'no_delly': False, 'no_lineage': False, 'add_variant_annotations': False, 'threads': 1, 'ram': 2, 'verbose': 0, 'delly_vcf': None, 'no_clean': False, 'func': <function main_profile at 0x7f7c66c09040>, 'software_name': 'tbprofiler', 'tmp_prefix': '493687b9-adf6-4587-9a29-48415323c925', 'files_prefix': './493687b9-adf6-4587-9a29-48415323c925', 'conf': {'snpEff_db': 'Mycobacterium_tuberculosis_h37rv', 'drugs': ['rifampicin', 'isoniazid', 'ethambutol', 'pyrazinamide', 'streptomycin', 'fluoroquinolones', 'moxifloxacin', 'ofloxacin', 'levofloxacin', 'ciprofloxacin', 'aminoglycosides', 'amikacin', 'capreomycin', 'kanamycin', 'cycloserine', 'ethionamide', 'clofazimine', 'para-aminosalicylic_acid', 'delamanid', 'bedaquiline', 'linezolid'], 'amplicon': False, 'files': {'ref': 'tbdb.fasta', 'gff': 'tbdb.gff', 'bed': 'tbdb.bed', 'version': 'tbdb.version.json', 'json_db': 'tbdb.dr.json', 'variables': 'tbdb.variables.json', 'spoligotype_spacers': 'tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': 'tbdb.spoligotype_list.csv', 'bedmask': 'tbdb.mask.bed', 'barcode': 'tbdb.barcode.bed'}, 'ref': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.fasta', 'gff': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.gff', 'bed': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.bed', 'version': {'name': 'tbdb', 'commit': 'c2fb9a2', 'Author': 'jodyphelan <jody.phelan@lshtm.ac.uk>', 'Date': 'Tue Oct 4 11:40:15 2022 +0100'}, 'variables': {'snpEff_db': 'Mycobacterium_tuberculosis_h37rv', 'drugs': ['rifampicin', 'isoniazid', 'ethambutol', 'pyrazinamide', 'streptomycin', 'fluoroquinolones', 'moxifloxacin', 'ofloxacin', 'levofloxacin', 'ciprofloxacin', 'aminoglycosides', 'amikacin', 'capreomycin', 'kanamycin', 'cycloserine', 'ethionamide', 'clofazimine', 'para-aminosalicylic_acid', 'delamanid', 'bedaquiline', 'linezolid'], 'amplicon': False, 'files': {'ref': 'tbdb.fasta', 'gff': 'tbdb.gff', 'bed': 'tbdb.bed', 'version': 'tbdb.version.json', 'json_db': 'tbdb.dr.json', 'variables': 'tbdb.variables.json', 'spoligotype_spacers': 'tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': 'tbdb.spoligotype_list.csv', 'bedmask': 'tbdb.mask.bed', 'barcode': 'tbdb.barcode.bed'}}, 'spoligotype_spacers': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.spoligotype_list.csv', 'bedmask': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.mask.bed', 'barcode': '/usr/local/anaconda3/envs/tbprofiler4/share/tbprofiler//tbdb.barcode.bed'}, 'run_delly': True}
```
## Traceback:
```
  File "/usr/local/anaconda3/envs/tbprofiler4/bin/tb-profiler", line 671, in <module>
    args.func(args)
  File "/usr/local/anaconda3/envs/tbprofiler4/bin/tb-profiler", line 151, in main_profile
    results.update(pp.run_profiler(args))
  File "/usr/local/anaconda3/envs/tbprofiler4/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 36, in run_profiler
    args.bam_file = get_bam_file(args)
  File "/usr/local/anaconda3/envs/tbprofiler4/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 100, in get_bam_file
    fastq_obj = untrimmed_fastq_obj.trim(args.files_prefix,threads=args.threads)
  File "/usr/local/anaconda3/envs/tbprofiler4/lib/python3.9/site-packages/pathogenprofiler/fastq.py", line 39, in trim
    run_cmd("trimmomatic PE -threads %(threads)s -phred33 %(r1)s %(r2)s -baseout %(prefix)s LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36" % vars(self))
  File "/usr/local/anaconda3/envs/tbprofiler4/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 409, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
```
## Value:
```
Command Failed:
set -u pipefail; trimmomatic PE -threads 1 -phred33 K192399_S128_R1.fastq.gz K192399_S128_R2.fastq.gz -baseout ./493687b9-adf6-4587-9a29-48415323c925 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
stderr:
TrimmomaticPE: Started with arguments:
 -threads 1 -phred33 K192399_S128_R1.fastq.gz K192399_S128_R2.fastq.gz -baseout ./493687b9-adf6-4587-9a29-48415323c925 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Using templated Output files: ./493687b9-adf6-4587-9a29-48415323c925_1P ./493687b9-adf6-4587-9a29-48415323c925_1U ./493687b9-adf6-4587-9a29-48415323c925_2P ./493687b9-adf6-4587-9a29-48415323c925_2U
Exception in thread "main" java.lang.RuntimeException: Invalid FASTQ comment line: @A00755:200:HMWTJDRXY:1:2270:6822:35383 1:N:0:ATTGGATGTG+CTTAAGGGAC
	at org.usadellab.trimmomatic.fastq.FastqParser.parseOne(FastqParser.java:82)
	at org.usadellab.trimmomatic.fastq.FastqParser.next(FastqParser.java:179)
	at org.usadellab.trimmomatic.TrimmomaticPE.processSingleThreaded(TrimmomaticPE.java:62)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:316)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
```

**Comment by jodyphelan** [comment]
Hi @ChiehYin,

It looks like trimmomatic is complaining about the fastq file:
```
Invalid FASTQ comment line: @A00755:200:HMWTJDRXY:1:2270:6822:35383 1:N:0:ATTGGATGTG+CTTAAGGGAC
```

It could be that your fastq is malformed. Could you check this by running it on a different sample (if you have access to one) and see if you get a similar error?

**Comment by ChiehYin** [comment]
Hi Jody,

Thanks for your reply! I did run on multiple samples which were in the same sequencing batch. Most of them worked well and produced the results.

**Comment by jodyphelan** [comment]
Ah ok, so it looks like it is an issue with just that fastq file then. If you have downloaded it from somewhere maybe you could try redownload, or if this is your only copy of the files then you could try fix it by looking at the file an identifying what is going on with this particular read.

With regards to your collate question. It depends on which version was used to produce the old files. Easiest way to check is by trying to run it and if you get an error, it most likely won't work and you'll need to run profiling again for all samples.

**Comment by ChiehYin** [comment]
Yes, I redownloaded the fastq files and they worked. Thanks for your reply!

**Comment by jodyphelan** [comment]
Great!
