### ISSUE TITLE
error running tb profile

### ISSUE THREAD

**Issue by AishaBell** [jodyphelan/TBProfiler#256]
This is the error report generated while running tb-profile. can you give us pointers on how to fix it. 
NB: Our read is not paired.

tb-profiler profile -1 ERR4403535.fastq
Traceback (most recent call last):
  File "/home/aishabisola/anaconda3/bin/tb-profiler", line 333, in <module>
    args.func(args)
  File "/home/aishabisola/anaconda3/bin/tb-profiler", line 82, in main_profile
    results = pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af)

**Comment by jodyphelan** [comment]
Hi @AishaBell,

Is the error reported longer than what you pasted or does it stop there?
