### ISSUE TITLE
My version is 4.3 and when I execute tb-profiler update_tbdb, the following message appears

### ISSUE THREAD

**Issue by jzhone** [jodyphelan/TBProfiler#287]
Running command:
set -u pipefail; git checkout master

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db  --load
Traceback (most recent call last):
  File "/home/seq/anaconda3/envs/tb4_3_copy/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/home/seq/anaconda3/envs/tb4_3_copy/bin/tb-profiler", line 200, in main_update_tbdb
    pp.run_cmd("tb-profiler create_db %s --load" % tmp)
  File "/home/seq/anaconda3/envs/tb4_3_copy/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 397, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db  --load
stderr:
Don't know how to handle this mutation: tlyA frameshift_variant

Cleaning up after failed run

**Comment by jodyphelan** [comment]
Hi @jzhone 

Between v4.3 and v4.4 there were a few changes which make the DB  from github incompatible with older versions. I would try upgrade to v4.4.2 and check if that works for you.

**Comment by jzhone** [comment]
Thanks for reply. Can I update the version via conda update? Or do I need to rebuild the new environment to install it with conda.

**Comment by jodyphelan** [comment]
I would recommend to build a new environment with conda
