### ISSUE TITLE
TBProfiler load_library cannot find newly created tbdb 

### ISSUE THREAD

**Issue by ryanjameskennedy** [jodyphelan/TBProfiler#313]
Upon running the following command:
```
tb-profiler load_library test
```
The following error was returned:
```
Traceback (most recent call last):
  File "/data/bnf/sw/miniconda3/envs/tbprofiler/bin/tb-profiler", line 565, in <module>
    args.func(args)
  File "/data/bnf/sw/miniconda3/envs/tbprofiler/bin/tb-profiler", line 213, in main_load_library
    pp.load_db(variables_file,args.software_name,source_dir=source_dir)
  File "/data/bnf/sw/miniconda3/envs/tbprofiler/lib/python3.12/site-packages/pathogenprofiler/db.py", line 564, in load_db
    shutil.copyfile(source,target)
  File "/data/bnf/sw/miniconda3/envs/tbprofiler/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/test.fasta'
```
The run works if you provide the filepath to the tbdb and the prefix to your newly created tbdb as so:
```
tb-profiler load_library /path/to/tbdb/test
```
But this is not the format provided on your [README ](https://github.com/jodyphelan/TBProfiler/blob/8020c5c26bff2b394d3509362e72dadbbd1c355d/README.md?plain=1#L148). Using the `--dir` command also doesn't work.

**Comment by jodyphelan** [comment]
Hi @ryanjameskennedy 

Thanks for letting me know about this. If you could create a PR that would be amazing!

**Comment by ryanjameskennedy** [comment]
Also realised that dependencies for `create_db` (like `pysam`) are missing from the singularity image from galaxy project.

**Comment by jodyphelan** [comment]
I'm planning to upgrade the installation to use `pyproject.toml` instead of `setup.py`. So will add the dependancies in there.

**Comment by ryanjameskennedy** [comment]
If you haven't gotten around to it I can give it a go next week:)
