### ISSUE TITLE
Collate issue

### ISSUE THREAD

**Issue by EtienneNtumba** [jodyphelan/TBProfiler#322]
b-profiler collate 
[04:57:16] INFO     Using ref file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.fasta                                                                                              db.py:594
           INFO     Using gff file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.gff                                                                                                db.py:594
           INFO     Using bed file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.bed                                                                                                db.py:594
           INFO     Using version file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.version.json                                                                                   db.py:594
           INFO     Using json_db file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.dr.json                                                                                        db.py:594
           INFO     Using variables file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.variables.json                                                                               db.py:594
           INFO     Using spoligotype_spacers file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.spoligotype_spacers.txt                                                            db.py:594
           INFO     Using spoligotype_annotations file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.spoligotype_list.csv                                                           db.py:594
           INFO     Using bedmask file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.mask.bed                                                                                       db.py:594
           INFO     Using barcode file: /home/p0129674/anaconda3/envs/my_pro/share/tbprofiler//tbdb.barcode.bed                                                                                    db.py:594
  0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/p0129674/anaconda3/envs/my_pro/bin/tb-profiler", line 562, in <module>
    args.func(args)
  File "/home/p0129674/anaconda3/envs/my_pro/bin/tb-profiler", line 253, in main_collate
    tbp.collate_results(args.prefix,args.conf,sample_file=args.samples,result_dirs=args.dir,mark_missing=args.mark_missing)
  File "/home/p0129674/anaconda3/envs/my_pro/lib/python3.8/site-packages/tbprofiler/collate.py", line 74, in collate_results
    if "missing_positions" in temp["qc"]:
KeyError: 'qc'
Cleaning up after failed run
           ERROR

**Comment by jodyphelan** [comment]
Hi @EtienneNtumba ,

Can you try replicate this error with the latest version (v6.2.0)? Let me know if it is still an issue.
