### ISSUE TITLE
[E::bcf_hdr_read] Input is not detected as bcf or vcf format

### ISSUE THREAD

**Issue by schorlton-bugseq** [jodyphelan/TBProfiler#367]
Thanks for all of your work on TBProfiler. Running;
```
tb-profiler profile --bam rpoB.bam --external_db tbdb/tbdb
```

This worked on v5, but now on v6.2.1 (installed from conda) getting the below error. My external_db as created with `update_db` and `--match_ref`, using the RefSeq H37Rv (NC_000962.3). As it cleans up (and I can't figure out if one can disable this?), I can't inspect the VCFs. Any ideas?

Thanks!

```bash
# tb-profiler error report

* OS: linux
* Program version: 6.2.1
* Database version: {'name': 'tbdb', 'commit': 'e6a0040', 'Merge': 'e3c6ce6 539a394', 'Author': 'Jody Phelan <jody.phelan@lshtm.ac.uk>', 'Date': 'Thu Mar 21 14:45:00 2024 +0000'}
* Program call:
\```
{'logging': 'DEBUG', 'read1': None, 'read2': None, 'bam': 'rpoB.bam', 'fasta': None, 'vcf': None, 'platform': 'illumina', 'db': 'tbdb', 'external_db': '/test/tbdb/tbdb', 'prefix': 'tbprofiler', 'csv': False, 'txt': False, 'text_template': None, 'docx': False, 'docx_template': None, 'add_columns': None, 'add_mutation_metadata': False, 'dir': '/test', 'depth': '0,10', 'af': '0,0.1', 'strand': '0,3', 'sv_depth': '0,10', 'sv_af': '0.5,0.9', 'sv_len': '100000,50000', 'mapper': 'bwa', 'caller': 'freebayes', 'calling_params': None, 'kmer_counter': 'kmc', 'coverage_tool': 'samtools', 'suspect': False, 'spoligotype': False, 'update_phylo': False, 'call_whole_genome': False, 'snp_dist': None, 'snp_diff_db': None, 'snp_diff_no_store': False, 'no_trim': False, 'no_coverage_qc': False, 'no_samclip': False, 'no_delly': False, 'no_lineage': False, 'add_variant_annotations': False, 'threads': 8, 'ram': 2, 'delly_vcf': None, 'supplementary_bam': None, 'no_clean': False, 'temp': '.', 'func': <function main_profile at 0x79718d914280>, 'software_name': 'tbprofiler', 'version': '6.2.1', 'tmp_prefix': 'ee6799dc-3f8e-4346-952c-f5e71e8cf5be', 'files_prefix': '/test/ee6799dc-3f8e-4346-952c-f5e71e8cf5be', 'conf': {'snpEff_db': 'Mycobacterium_tuberculosis_h37rv', 'drugs': ['rifampicin', 'isoniazid', 'ethambutol', 'pyrazinamide', 'moxifloxacin', 'levofloxacin', 'bedaquiline', 'delamanid', 'pretomanid', 'linezolid', 'streptomycin', 'amikacin', 'kanamycin', 'capreomycin', 'clofazimine', 'ethionamide', 'para-aminosalicylic_acid', 'cycloserine'], 'tb-profiler-version': '>=6.0.0,<7.0.0', 'version': {'name': 'tbdb', 'commit': 'e6a0040', 'Merge': 'e3c6ce6 539a394', 'Author': 'Jody Phelan <jody.phelan@lshtm.ac.uk>', 'Date': 'Thu Mar 21 14:45:00 2024 +0000'}, 'amplicon': False, 'chromosome_conversion': {'target': ['Chromosome'], 'source': ['NC_000962.3']}, 'files': {'ref': 'tbdb.fasta', 'gff': 'tbdb.gff', 'bed': 'tbdb.bed', 'json_db': 'tbdb.dr.json', 'variables': 'tbdb.variables.json', 'spoligotype_spacers': 'tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': 'tbdb.spoligotype_list.csv', 'bedmask': 'tbdb.mask.bed', 'barcode': 'tbdb.barcode.bed', 'rules': 'tbdb.rules.txt'}, 'ref': '/test/tbdb/tbdb.fasta', 'gff': '/test/tbdb/tbdb.gff', 'bed': '/test/tbdb/tbdb.bed', 'variables': {'snpEff_db': 'Mycobacterium_tuberculosis_h37rv', 'drugs': ['rifampicin', 'isoniazid', 'ethambutol', 'pyrazinamide', 'moxifloxacin', 'levofloxacin', 'bedaquiline', 'delamanid', 'pretomanid', 'linezolid', 'streptomycin', 'amikacin', 'kanamycin', 'capreomycin', 'clofazimine', 'ethionamide', 'para-aminosalicylic_acid', 'cycloserine'], 'tb-profiler-version': '>=6.0.0,<7.0.0', 'version': {'name': 'tbdb', 'commit': 'e6a0040', 'Merge': 'e3c6ce6 539a394', 'Author': 'Jody Phelan <jody.phelan@lshtm.ac.uk>', 'Date': 'Thu Mar 21 14:45:00 2024 +0000'}, 'amplicon': False, 'chromosome_conversion': {'target': ['Chromosome'], 'source': ['NC_000962.3']}, 'files': {'ref': 'tbdb.fasta', 'gff': 'tbdb.gff', 'bed': 'tbdb.bed', 'json_db': 'tbdb.dr.json', 'variables': 'tbdb.variables.json', 'spoligotype_spacers': 'tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': 'tbdb.spoligotype_list.csv', 'bedmask': 'tbdb.mask.bed', 'barcode': 'tbdb.barcode.bed', 'rules': 'tbdb.rules.txt'}}, 'spoligotype_spacers': '/test/tbdb/tbdb.spoligotype_spacers.txt', 'spoligotype_annotations': '/test/tbdb/tbdb.spoligotype_list.csv', 'bedmask': '/test/tbdb/tbdb.mask.bed', 'barcode': '/test/tbdb/tbdb.barcode.bed', 'rules': ['Variant(gene_name=mmpL5,type=lof) inactivates_resistance Variant(gene_name=mmpR5)', 'Variant(gene_name=eis,type=lof) inactivates_resistance Variant(gene_name=eis)'], 'variant_filters': {'depth_hard': 0, 'depth_soft': 10, 'af_hard': 0, 'af_soft': 0.1, 'strand_hard': 0, 'strand_soft': 3, 'sv_depth_hard': 0, 'sv_depth_soft': 10, 'sv_af_hard': 0.5, 'sv_af_soft': 0.9, 'sv_len_hard': 100000, 'sv_len_soft': 50000}}, 'run_delly': True, 'samclip': True, 'coverage_qc': True, 'data_source': 'bam', 'call_lineage': True}
\```
## Traceback:
\```
  File "/opt/conda/envs/test/bin/tb-profiler", line 587, in <module>
    args.func(args)
  File "/opt/conda/envs/test/bin/tb-profiler", line 101, in main_profile
    variants_profile = pp.run_profiler(args)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/pathogenprofiler/cli.py", line 192, in run_profiler
    get_vcf_file(args)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/pathogenprofiler/cli.py", line 174, in get_vcf_file
    args.vcf = get_vcf_from_bam(args)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/pathogenprofiler/cli.py", line 157, in get_vcf_from_bam
    run_cmd("bcftools concat %s %s | bcftools sort -Oz -o %s" % (vcf_obj.filename,delly_vcf_obj.filename,final_target_vcf_file))
  File "/opt/conda/envs/test/lib/python3.10/site-packages/pathogenprofiler/utils.py", line 486, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
\```
## Value:
\```
Command Failed:
/bin/bash -c set -o pipefail; bcftools concat /test/ee6799dc-3f8e-4346-952c-f5e71e8cf5be.short_variants.targets.vcf.gz /test/ee6799dc-3f8e-4346-952c-f5e71e8cf5be.delly.targets.vcf.gz | bcftools sort -Oz -o /test/ee6799dc-3f8e-4346-952c-f5e71e8cf5be.targets.vcf.gz
stderr:
Checking the headers and starting positions of 2 files
[W::bcf_hdr_merge] Trying to combine "GQ" tag definitions of different types
Different sample names in /test/ee6799dc-3f8e-4346-952c-f5e71e8cf5be.delly.targets.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
Writing to /tmp/bcftools.A2ev5A
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Could not read VCF/BCF headers from -
Cleaning
\```
```

**Comment by jodyphelan** [comment]
Hi @marvinkobit 

Sorry for the delay in getting back to you on this. You can use `--no_clean` to stop removal of th intermediate files. This might be a tricky one to debug as it could be a variety of issues that cause failure to make the vcf. Feel free to drop me an email (my email is in the database version dictionary), if you get stuck and I'd be happy to help.

**Comment by schorlton-bugseq** [comment]
Thanks. The `--no_clean` helped. I think I finally got this, with two issues:
- BAM needs read group assigned (I see previous issue https://github.com/jodyphelan/TBProfiler/issues/161 so I guess I'm not the first; may I suggest TB-profiler explicitly warns+exits if BAM is missing the proper RG tag?
- RG tag needs to match BAM filename, because freebayes and delly get sample name from different places? Again, I think an explicit warning (or fixing this behaviour if possible) would be very useful.

Thanks again for your consideration!

**Comment by jodyphelan** [comment]
Thanks for debugging this! Definitely would be useful to add some sanity checks. Will get those in into the next version.

**Comment by schorlton-bugseq** [comment]
New challenge with this:

- After adding read group to a BAM, v6 runs but seems to miss a variant
- I recreated this in v5 because v5 can run with/without read group tags:
    - without rg in BAM, detects the variant
    - with rg, misses it

v5 example:
(needed to gz it for GitHub so please uncompress): 
[no_rg.bam.gz](https://github.com/user-attachments/files/16107947/no_rg.bam.gz)


```bash
docker run --rm -it quay.io/biocontainers/tb-profiler:5.0.1--pyhdfd78af_1

# finds variant
tb-profiler profile --bam no_rg.bam -p no_rg

# add read group
samtools addreplacerg -u -o rg.bam -r 'ID:rg SM:rg' no_rg.bam

# misses variant
tb-profiler profile --bam rg.bam -p rg
```

Thoughts on what could be causing this?

Thanks again for your help!

**Comment by jodyphelan** [comment]
The bam header is a pit picky with whitespace. Try adding the RG with:

```
samtools addreplacerg -u -o rg.bam -r 'ID:rg\tSM:rg' no_rg.bam
```

**Comment by jodyphelan** [comment]
Great thanks for helping debug!

**Comment by mariaelf97** [comment]
@jodyphelan I am having similar issues, but I am passing fastq files rather than a bam file. Can I ask for help on this?

Snakemake rule 
```

rule tb_profiler_profile:
    input:
        r1=output_path + "{isolate}/reads_1.fastq",
        r2=output_path + "{isolate}/reads_2.fastq"
    output:
        output_path + "{isolate}/tbprofiler/results/tbprofiler.results.json"
    params:
        profile_dir=directory(output_path + "{isolate}/tbprofiler")
    conda:
        "tb-profiler"
    shell:
        """
        mkdir -p {params.profile_dir} && cd {params.profile_dir} && \
        tb-profiler profile --read1 {input.r1} --read2 {input.r2} \
        --mapper minimap2 --caller freebayes --no_clean
        """
```

reads passed here look like:
```
@simulated.1/1
GGCACGGCGCGCGGGTGATCGAGCGGGACGGCAAGCACGACTCGGGAACAACCCCGAGCTGCCCGGGGCACGGGCCGCGCTGGGCCGGTGATCGGCGCGGACGTTCCGCGGGATTCCCAGCGTGCCAGGGTGTACGCGGCCGAGGCGTTC
+
IHHHIHHHHIIH!HIHIIIGFGHEIHIIGIDHGIFIGIHIGEHIDIHEGHHFIDHFII>AFIEFGIEIE@FIIHGGIIHIG?<HCIIFFIIEI=IG?FIIII:GIDEIAIIEGIIB@IIDIDDD@57FIIII@IIH?IIB>IIE8=I;AI
@simulated.2/1
CGCCGCGGTGGCCACCCGGCGCGCCCGCACGCGCATCGGCGACACCGTCGGCCAGTTCTGCCCTACCGCCGGTAGCGCAAGCACGTCGTCCACATAACGCTGCACCGATGCCACCGAACCGAACCGACCTTCTGGGGGCAGCGTCAACTG
+
HHIIHHIHIHHHHIHIGIHIGHGGFHIHGGGGIIE!HHEIICHHFGEGHIIGIHGIEIIGHICHIIIIADFF;?IIAIII@IIIFICHHHIIIG>BICIEII8IAHIIIIIGIHIIIIC>IIIIDH<IIIC:FI:IIHE67C=HII4IEI
@simulated.3/1
GAGCGGGACGGCAAGCACGACTCGGGAACAACCCCGAGCTGCCCGGGGCACGGGCCGCGCTGGGCCGGTGATCGGCGCGGACGTTCTGCGGGATTCCCAGCGTGCCAGGGTGTACGCGGCCGAGGCGTTCGTCCGGACCTTGTTCGACCG
```

error says

```
ValueError: Command Failed:
/bin/bash -c set -o pipefail; minimap2 --MD -t 1 -R '@RG\tID:tbprofiler\tSM:tbprofiler\tPL:illumina' -a -ax sr /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/tbdb.fasta /storage/mahmadi/tb_seqs/simulations/combinations/200/GCA_014900675.1_0.4_NZ_CP048071.1_0.6/tbprofiler/d32cfa12-8449-4037-b8ca-ffa51502bb72_TU| samtools sort -@ 1 -o /storage/mahmadi/tb_seqs/simulations/combinations/200/GCA_014900675.1_0.4_NZ_CP048071.1_0.6/tbprofiler/d32cfa12-8449-4037-b8ca-ffa51502bb72.single.bam -
stderr:
[M::mm_idx_gen::0.091*1.01] collected minimizers
[M::mm_idx_gen::0.126*1.00] sorted minimizers
[M::main::0.126*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.126*1.00] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.131*1.00] distinct minimizers: 722547 (99.04% are singletons); average occurrences: 1.018; average spacing: 5.998; total length: 4411532
minimap2: map.c:432: worker_for: Assertion `s->n_seg[i] <= 255' failed.
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "-"
```


tb-profiler version is 6.6.5


Thank you!

**Comment by mariaelf97** [comment]
These are reads simulated using mason, I also tried wgsim but it fails like:
 ```
wgsim ~/tb_seqs/H37Rv/H37Rv.fasta reads1.fq reads2.fq

tb-profiler profile --read1 reads1.fq --read2 reads2.fq --mapper minimap2 --caller freebayes
```
error

```
           ERROR    Delly failed, skipping                                                                                  bam.py:96
           INFO     Running snpEff                                                                                         vcf.py:108
           ERROR    Writing to /tmp/bcftools.f95rpV                                                                      utils.py:551
                    Error: LinkageError occurred while loading main class org.snpeff.SnpEff                                          
                            java.lang.UnsupportedClassVersionError: org/snpeff/SnpEff has been compiled by a more recent             
                    version of the Java Runtime (class file version 65.0), this version of the Java Runtime only                     
                    recognizes class file versions up to 61.0                                                                        
                    [E::bcf_hdr_read] Input is not detected as bcf or vcf format                                                     
                    Could not read VCF/BCF headers from -                                                                            
                    Cleaning                                                                                                         
                                                                                                                                     
Traceback (most recent call last):
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/bin/tb-profiler", line 707, in <module>
    args.func(args)
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/bin/tb-profiler", line 122, in wrapper
    func(args)
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/bin/tb-profiler", line 141, in main_profile
    variants_profile = pp.run_profiler(args)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/cli.py", line 212, in run_profiler
    annotated_variants = vcf_profiler(args)
                         ^^^^^^^^^^^^^^^^^^
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/profiler.py", line 70, in vcf_profiler
    annotated_variants = vcf_variant_profiler(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/profiler.py", line 90, in vcf_variant_profiler
    vcf_obj = vcf_obj.run_snpeff(conf["snpEff_db"],conf["ref"],conf["gff"],rename_chroms=conf.get("chromosome_conversion",None),bam_for_phasing=bam_for_phasing, db_dir=db_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/vcf.py", line 128, in run_snpeff
    run_cmd("bcftools view -a %(filename)s | bcftools view -c 1 | realign_tandem_deletions.py - %(ref_file)s %(gff_file)s - |  combine_vcf_variants.py --ref %(ref_file)s --gff %(gff_file)s %(phasing_bam)s | %(rename_cmd)s snpEff ann %(snpeff_config_opt)s -noLog -noStats %(db)s - %(re_rename_cmd)s | bcftools sort -Oz -o %(vcf_csq_file)s" % vars(self))
  File "/storage/mahmadi/mambaforge/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/utils.py", line 553, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
ValueError: Command Failed:
/bin/bash -c set -o pipefail; bcftools view -a /storage/mahmadi/git_repos/modjadji-tb-scheme/src/simulations/c24e8029-4176-45ad-80d4-d9812962ede0.targets_for_profile.vcf.gz | bcftools view -c 1 | realign_tandem_deletions.py - /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/tbdb.fasta /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/tbdb.gff - |  combine_vcf_variants.py --ref /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/tbdb.fasta --gff /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/tbdb.gff --bam /storage/mahmadi/git_repos/modjadji-tb-scheme/src/simulations/c24e8029-4176-45ad-80d4-d9812962ede0.bam |  snpEff ann -config /storage/mahmadi/mambaforge/envs/tb-profiler/share/tbprofiler/snpeff/snpEff.config -noLog -noStats Mycobacterium_tuberculosis_h37rv -  | bcftools sort -Oz -o /storage/mahmadi/git_repos/modjadji-tb-scheme/src/simulations/c24e8029-4176-45ad-80d4-d9812962ede0.targets_for_profile.csq.vcf.gz
stderr:
Writing to /tmp/bcftools.f95rpV
Error: LinkageError occurred while loading main class org.snpeff.SnpEff
        java.lang.UnsupportedClassVersionError: org/snpeff/SnpEff has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Could not read VCF/BCF headers from -
Cleaning
```

**Comment by jodyphelan** [comment]
Hi @mariaelf97 looks like the two errors are different.

For the first case (the snakemake one) - would you be able to run `fq lint` (from [here](https://anaconda.org/bioconda/fq)) on the faste files and paste the result?

For the second one - I think this is an issue with the version of snpEff being installed. If you're using conda try install v5.2 and this should fix that particular issue.

**Comment by mariaelf97** [comment]
Hi @jodyphelan Thank you so much for the response. snpeff version installed automatically seems to be V5.3- just downgraded and it solved the issue but the fastq issue persists.

```
version is fq 0.12.0 (2024-07-08)
fq lint reads1.fq reads2.fq --lint-mode log
2025-10-30T20:31:05.208743Z  INFO fq::commands::lint: fq-lint start
2025-10-30T20:31:05.208766Z  INFO fq::commands::lint: validating paired end reads
2025-10-30T20:31:05.208772Z  INFO fq::validators: disabled validators: []
2025-10-30T20:31:05.208780Z  INFO fq::validators: enabled single read validators: ["[S003] NameValidator", "[S004] CompleteValidator", "[S002] AlphabetValidator", "[S001] PlusLineValidator", "[S005] ConsistentSeqQualValidator", "[S006] QualityStringValidator"]
2025-10-30T20:31:05.208787Z  INFO fq::validators: enabled paired read validators: ["[P001] NamesValidator"]
2025-10-30T20:31:05.208912Z  INFO fq::commands::lint: enabled special validators: ["[S007] DuplicateNameValidator"]
2025-10-30T20:31:05.208916Z  INFO fq::commands::lint: starting validation (pass 1)
2025-10-30T20:31:06.005309Z  INFO fq::commands::lint: read 1000000 * 2 records
2025-10-30T20:31:06.005329Z  INFO fq::commands::lint: starting validation (pass 2)
2025-10-30T20:31:06.214304Z  INFO fq::commands::lint: read 1000000 records
2025-10-30T20:31:06.216394Z  INFO fq::commands::lint: fq-lint end
```

**Comment by jodyphelan** [comment]
So do the wgsim reads pass through ok?

What is the mason command you are using to simulate?

**Comment by mariaelf97** [comment]
no actually they both fail. The mason command is as following:
```
mason_simulator -ir amplicon.fasta -n 200 -o reads1.fastq -or reads2.fastq 
```


it does successfully run on illumina sequencer reads like:
```
@VH01272:91:AAGKM27M5:1:1101:22208:1000 1:N:0:TACAAGACTT+TGAACACCTG
GCACCAGGGCGTGCAGGCGTGCCTCCAGCTCCGCCAGCTCGAAAGGTTTGGCCAGAAAGTCGTCTGCGCCAGCGTTGAGCAGGCGCACCCGCTCGTCCAGCGAATCACGCGCCGTCAGAATCAGCGCGGGCAGGCGTTGGTCGCGTTCGCG
+
IIIIIII99III9IIIIIII9IIIIIII9II-II9I9IIIIII99III9II9I9III9I9II9II9II9II9IIIIIIIII99IIIIIIIIIII9IIIIII-IIIIII-II9IIIIIIIIIIII99IIIIIIIII9II9IIIIIIIIIII-
@VH01272:91:AAGKM27M5:1:1101:29252:1000 1:N:0:TACAAGACTT+TGAACACCTG
CGCTCATGCACGAAAGCGTGGGGAGCGAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGGTGGGTACTAGGTGTGGGTTTCCTTCCTTTAGGGATCCGTGCCGTAGCTAACGCATTAAGTACCCCGCCTGGGGAGTACGGCCGCA
```

I wonder if read header is the issue and if so, what pattern does it need to follow?

**Comment by mariaelf97** [comment]
[reads_1.fastq.gz](https://github.com/user-attachments/files/23266731/reads_1.fastq.gz)
[reads_2.fastq.gz](https://github.com/user-attachments/files/23266732/reads_2.fastq.gz)

@jodyphelan example files!
