### ISSUE TITLE
Problem in running the profile pipeline

### ISSUE THREAD

**Issue by ngs12321sgn** [jodyphelan/TBProfiler#369]
Dear all,

How to solve vthis problem?

My command line is

time tb-profiler profile -1 T25A_1.fastq.gz -2 T25A_2.fastq.gz -t 24 -p T25A --txt

Please help.

Thank you

Regards
Chin
Malaysia

Running command:
set -u pipefail; samtools merge -@ 24 -f ./f512ea62-0db3-4011-bcea-16b2271a49aa.unsort.bam ./f512ea62-0db3-4011-bcea-16b2271a49aa.pair.bam ./f512ea62-0db3-4011-bcea-16b2271a49aa.single.bam

Running command:
set -u pipefail; samtools sort -m 768M -n -@ 24  ./f512ea62-0db3-4011-bcea-16b2271a49aa.unsort.bam | samtools fixmate -@ 24 -m - - | samtools sort -m 768M -@ 24 - | samtools markdup -@ 24 - ./f512ea62-0db3-4011-bcea-16b2271a49aa.bam

Running command:
set -u pipefail; rm ./f512ea62-0db3-4011-bcea-16b2271a49aa.single.bam ./f512ea62-0db3-4011-bcea-16b2271a49aa.pair.bam ./f512ea62-0db3-4011-bcea-16b2271a49aa.unsort.bam

Running command:
set -u pipefail; samtools index -@ 24 ./f512ea62-0db3-4011-bcea-16b2271a49aa.bam
Using ./f512ea62-0db3-4011-bcea-16b2271a49aa.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.
Traceback (most recent call last):
  File "/root/miniconda3/bin/tb-profiler", line 693, in <module>
    args.func(args)
  File "/root/miniconda3/bin/tb-profiler", line 152, in main_profile
    results.update(pp.run_profiler(args))
  File "/root/miniconda3/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 37, in run_profiler
    results = bam_profiler(
  File "/root/miniconda3/lib/python3.9/site-packages/pathogenprofiler/profiler.py", line 30, in bam_profiler
    vcf_obj = bam_obj.call_variants(conf["ref"], caller=caller, bed_file=conf["bed"], threads=threads, calling_params=calling_params, samclip = samclip, min_dp=min_depth)
  File "/root/miniconda3/lib/python3.9/site-packages/pathogenprofiler/bam.py", line 82, in call_variants
    run_cmd('%(windows_cmd)s | parallel -j %(threads)s --col-sep " " "%(calling_cmd)s"' % vars(self))
  File "/root/miniconda3/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 394, in run_cmd
    raise ValueError("Cant find programs: %s\n" % (", ".join(missing)))
ValueError: Cant find programs: bcftools

Cleaning up after failed run

################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (T25A.errlog.txt)

###############################################################################

**Comment by jodyphelan** [comment]
Hi @ngs12321sgn 

Did you use conda to install or a different method? It seems that you are missing `bcftools` which is a dependancy for `tb-profiler`.
