### ISSUE TITLE
update_tbdb-Unable to update the database

### ISSUE THREAD

**Issue by BhawnaY16** [jodyphelan/TBProfiler#376]
Hey,
I have installed tbprofiler using bioconda and I was trying to update the database.
I ma getting this error -
TBProfiler version 4.3.0
(mytools) user@user-PowerEdge-R820:/media/user/36d81ee3-f383-4bc4-b619-20abd785be33$ tb-profiler update_tbdb

Running command:
set -u pipefail; git checkout master

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db  --load
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mytools/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/home/user/miniconda3/envs/mytools/bin/tb-profiler", line 200, in main_update_tbdb
    pp.run_cmd("tb-profiler create_db %s --load" % tmp)
  File "/home/user/miniconda3/envs/mytools/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 397, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db  --load
stderr:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mytools/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/home/user/miniconda3/envs/mytools/bin/tb-profiler", line 219, in main_create_db
    pp.create_db(args,extra_files=extra_files)
  File "/home/user/miniconda3/envs/mytools/lib/python3.7/site-packages/pathogenprofiler/db.py", line 556, in create_db
    mutation_lookup = get_snpeff_formated_mutation_list(args.csv,"genome.fasta","genome.gff",json.load(open("variables.json"))["snpEff_db"])
  File "/home/user/miniconda3/envs/mytools/lib/python3.7/site-packages/pathogenprofiler/db.py", line 193, in get_snpeff_formated_mutation_list
    for row in csv.DictReader(open(csv_file)):
FileNotFoundError: [Errno 2] No such file or directory: 'tbdb.csv'
Cleaning up after failed run
Do I need to manually create_db then update?How to resolve this error if you can please help

**Comment by BhawnaY16** [comment]
Hey,
I resolved it by making new conda env and downloading new tb-profiler version.
Then I updated the database. I faced delly issue while processing my data, which I resolved by downloading delly and other few libraries.It worked!

Thanks

**Comment by jodyphelan** [comment]
Great to hear you have fixed this issue!
