### ISSUE TITLE
Difference between results of installed tbprofiler pipeline and online version

### ISSUE THREAD

**Issue by RehmanZaira** [jodyphelan/TBProfiler#389]
Hi,
I am analyzing the same data through installed tbprofiler and the online version. I got the Delamanid resistance when using the online version. The version of tbprofier that I am using is 5.0.1. 
I am trying to update the tbprofiler but got an error
(env_tbprofiler) ngs@ngs-srv:~$ tb-profiler update_tbdb
[10:43:09] ERROR    Traceback (most recent call last):              utils.py:391
                      File                                                      
                    "/home/ngs/miniconda3/envs/env_tbprofiler/bin/t             
                    b-profiler", line 562, in <module>                          
                        args.func(args)                                         
                      File                                                      
                    "/home/ngs/miniconda3/envs/env_tbprofiler/bin/t             
                    b-profiler", line 205, in main_create_db                    
                        pp.create_db(args,extra_files=extra_files)              
                      File                                                      
                    "/home/ngs/miniconda3/envs/env_tbprofiler/lib/p             
                    ython3.10/site-packages/pathogenprofiler/db.py"             
                    , line 417, in create_db                                    
                        hgvs_variants = [r for r in                             
                    csv.DictReader(open(args.csv))]                             
                    FileNotFoundError: [Errno 2] No such file or                
                    directory: 'tbdb.csv'                                       
                    Cleaning up after failed run                                
                                                                                
Traceback (most recent call last):
  File "/home/ngs/miniconda3/envs/env_tbprofiler/bin/tb-profiler", line 562, in <module>
    args.func(args)
  File "/home/ngs/miniconda3/envs/env_tbprofiler/bin/tb-profiler", line 183, in main_update_tbdb
    pp.run_cmd(f"tb-profiler create_db --prefix {args.prefix} {tmp} --load")
  File "/home/ngs/miniconda3/envs/env_tbprofiler/lib/python3.10/site-packages/pathogenprofiler/utils.py", line 392, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
ValueError: Command Failed:
/bin/bash -c set -o pipefail; tb-profiler create_db --prefix tbdb  --load
stderr:
Traceback (most recent call last):
  File "/home/ngs/miniconda3/envs/env_tbprofiler/bin/tb-profiler", line 562, in <module>
    args.func(args)
  File "/home/ngs/miniconda3/envs/env_tbprofiler/bin/tb-profiler", line 205, in main_create_db
    pp.create_db(args,extra_files=extra_files)
  File "/home/ngs/miniconda3/envs/env_tbprofiler/lib/python3.10/site-packages/pathogenprofiler/db.py", line 417, in create_db
    hgvs_variants = [r for r in csv.DictReader(open(args.csv))]
FileNotFoundError: [Errno 2] No such file or directory: 'tbdb.csv'
Cleaning up after failed run

Cleaning up after failed run
           ERROR                                                  tb-profiler:58
                                                                                
                    ################################# ERROR                     
                    #######################################                     
                                                                                
                    This run has failed. Please check all                       
                    arguments and make sure all input files                     
                    exist. If no solution is found, please open                 
                    up an issue at                                              
                    https://github.com/jodyphelan/TBProfiler/issu               
                    es/new and paste or attach the                              
                    contents of the error log (tbdb.errlog.txt)                 
                                                                                
                    #############################################               
                    ##################################                          

Kindly guide me how to fix that issue.

**Comment by RehmanZaira** [comment]
Hi Jody,
I am waiting for your response.

**Comment by RehmanZaira** [comment]
Hi @jodyphelan,
I have installed the updated version of tb-profiler 6.5.0. I have the data of sample that was run previously on web version a month ago. When I run the same sample on the updated version i found discrepancy in the Delamanid resistance. Previously it was deletion in fbic gene and in the current version it is in fbib gene and it is gain of stop codon. Can you please tell me which reference genome is used in the current version as the previous version uses H37rv?

**Comment by jodyphelan** [comment]
There is an issue with the variant calling process which places a deletion in fbiC (see https://github.com/jodyphelan/TBProfiler/issues/344). In recent versions this has been corrected, so you should use the results from the more recent version. The same version of the reference genome has been used.

**Comment by RehmanZaira** [comment]
Thank you for the clarification. In the new version of Tb-profiler, I didn't get any vcf files. The vcf folder is empty.

**Comment by jodyphelan** [comment]
What was the command you used to run the pipeline?

**Comment by RehmanZaira** [comment]
HI @jodyphelan when I run the new version of tbprofiler, I didn't get any .vcf files in the vcf folder.

**Comment by jodyphelan** [comment]
Which options did you use when run run the tb-profiler command?
