### ISSUE TITLE
Can I switch to just analyzing the WHO results?

### ISSUE THREAD

**Issue by jzhone** [jodyphelan/TBProfiler#396]
I see on top of mutations.csv or tbdb.dr.json that the WHO branch is already included. When I use version 6.3.0, can I switch to just analyzing the WHO results?

**Comment by jodyphelan** [comment]
Hi @jzhone 

You can run `tb-profiler update_tbdb --branch who` to install the WHO-only database. 
In subsequent runs just remember to use `--db who` to use that database

**Comment by justicengom** [comment]
Good morning @jodyphelan 
I an "tb-profiler update_tbdb --branch who"

then a got this: 
Traceback (most recent call last):
  File "/home/justicengom/miniconda3/envs/tb-profiler/bin/tb-profiler", line 664, in <module>
    args.func(args)
  File "/home/justicengom/miniconda3/envs/tb-profiler/bin/tb-profiler", line 249, in main_update_tbdb
    pp.run_cmd(f"tb-profiler create_db --prefix {args.prefix} --csv mutations.csv --watchlist watchlist.csv {extra_args} --load")
  File "/home/justicengom/miniconda3/envs/tb-profiler/lib/python3.12/site-packages/pathogenprofiler/utils.py", line 537, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
ValueError: Command Failed:
/bin/bash -c set -o pipefail; tb-profiler create_db --prefix who --csv mutations.csv --watchlist watchlist.csv  --load
stderr:

Cleaning up after failed run
           ERROR

**Comment by justicengom** [comment]
6.4.1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
