### ISSUE TITLE
paftools error

### ISSUE THREAD

**Issue by cmfield** [jodyphelan/TBProfiler#401]
I am running `tb-profiler profile --fasta` but getting an error:

```
[11:11:38] DEBUG    Running command: cat /mnt/data/fieldc/tasks/tbprofiler_20241106/temp/6ed34549-84a0-4203-a918-60beddb4bd5d.paf | paftools.js call -l 100 -L 100 -f                             utils.py:529
                    /mnt/data/software_stack/easybuild/software/Python/3.11.3-GCCcore-12.3.0/share/tbprofiler//tbdb.fasta -s tbprofiler - | add_dummy_AD.py | bcftools view -Oz -o
                    /mnt/data/fieldc/tasks/tbprofiler_20241106/temp/6ed34549-84a0-4203-a918-60beddb4bd5d.vcf.gz
           ERROR    /mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:150: TypeError: Cannot read properties of null (reading 'set')                       utils.py:534
                                    } else seq.set(buf);
                                 ^
                    TypeError: Cannot read properties of null (reading 'set')
                        at fasta_read (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:150:14)
                        at paf_call (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:350:31)
                        at main (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:3651:26)
                        at /mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:3669:1
                    Failed to read from standard input: unknown file type

Traceback (most recent call last):
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/bin/tb-profiler", line 645, in <module>
    args.func(args)
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/bin/tb-profiler", line 115, in main_profile
    variants_profile = pp.run_profiler(args)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/lib/python3.11/site-packages/pathogenprofiler/cli.py", line 199, in run_profiler
    get_vcf_file(args)
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/lib/python3.11/site-packages/pathogenprofiler/cli.py", line 175, in get_vcf_file
    args.vcf = Paf(args.paf).get_ref_variants(args.conf["ref"], args.prefix, args.files_prefix)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/lib/python3.11/site-packages/pathogenprofiler/fasta.py", line 143, in get_ref_variants
    run_cmd("cat %(filename)s | paftools.js call -l 100 -L 100 -f %(refseq)s -s %(sample_name)s - | add_dummy_AD.py | bcftools view -Oz -o %(file_prefix)s.vcf.gz" % vars(self))
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.0-foss-2023a/lib/python3.11/site-packages/pathogenprofiler/utils.py", line 536, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,result.stderr.decode()))
ValueError: Command Failed:
/bin/bash -c set -o pipefail; cat /mnt/data/fieldc/tasks/tbprofiler_20241106/temp/6ed34549-84a0-4203-a918-60beddb4bd5d.paf | paftools.js call -l 100 -L 100 -f /mnt/data/software_stack/easybuild/software/Python/3.11.3-GCCcore-12.3.0/share/tbprofiler//tbdb.fasta -s tbprofiler - | add_dummy_AD.py | bcftools view -Oz -o /mnt/data/fieldc/tasks/tbprofiler_20241106/temp/6ed34549-84a0-4203-a918-60beddb4bd5d.vcf.gz
stderr:
/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:150: TypeError: Cannot read properties of null (reading 'set')
                } else seq.set(buf);
             ^
TypeError: Cannot read properties of null (reading 'set')
    at fasta_read (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:150:14)
    at paf_call (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:350:31)
    at main (/mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:3651:26)
    at /mnt/data/software_stack/easybuild/software/minimap2/2.26-GCCcore-12.3.0/bin/paftools.js:3669:1
Failed to read from standard input: unknown file type
```
[tbprofiler.errlog.txt](https://github.com/user-attachments/files/17645447/tbprofiler.errlog.txt)

minimap2 version 2.26 if that helps.

**Comment by cmfield** [comment]
I'd like to say I know where the error lay but I'm not sure. I updated paftools.js to 2.28 after reading somewhere that it might not like fasta headers with spaces in. That caused issues with the non-fasta files which were referencing only 'Chromosome'. I changed the fasta header to just 'Chromosome' but that didn't solve those issues. I updated tbdb and then it worked.

Then I reinstalled without these changes to see if I could recreate the issues or solution and.. it just worked.. so I'm at a loss. I'll close without resolution other than maybe update minimap?
