### ISSUE TITLE
Blank output with --docx --docx_template default_template.docx 

### ISSUE THREAD

**Issue by cmfield** [jodyphelan/TBProfiler#408]
A Word file is produced, but none of the reported resistances in the .txt file are listed in the table. I got the template from your other repository.

This is currently with 6.3.0 (6.4.0 isn't compatible with the most recent release of pathogen profiler and I have to use versioned software), docxcompose 1.4.0, docxtpl 0.17.0 - any other relevant packages let me know.

**Comment by cmfield** [comment]
The problem is that 6.4.0+ cause this error with pathogen-profiler 4.4.0:

```
Traceback (most recent call last):
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.1-foss-2023a/bin/tb-profiler", line 664, in <module>
    args.func(args)
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.1-foss-2023a/bin/tb-profiler", line 109, in wrapper
    func(args)
  File "/mnt/data/software_stack/easybuild/software/TBProfiler/6.4.1-foss-2023a/bin/tb-profiler", line 132, in main_profile
    rules_applied = pp.apply_rules(args.conf['rules'], variants_profile, just_make_note=True if args.implement_rules==False else False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: apply_rules() got an unexpected keyword argument 'just_make_note'
```

**Comment by jodyphelan** [comment]
Oh yes it  this is a new feature that was introduced in pathogen-profiler v4.5.0+.
Could you try cupdate pathogen-profiler from 4.4.0 to 4.5.1? If you are installing through conda then it should automatically install the right version of pathogen-profiler.

https://github.com/bioconda/bioconda-recipes/blob/66455fb30d0169d2539d18b339c5c8b5880b4f7a/recipes/tb-profiler/meta.yaml#L32

**Comment by cmfield** [comment]
I updated to tbprofiler 6.5.0, pathogen-profiler 4.6.0.

I get the error:

```raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
docx.opc.exceptions.PackageNotFoundError: Package not found at etc..```

It appears to be looking for default_template.docx in the share directory of my Python installation, instead of where I have the python packages themselves installed (they are elsewhere), and is ignoring --docx_template when I give the explicit path.
