### ISSUE TITLE
KeyError:530 when running the pipeline

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#55]
Hi Jody, 

    I am getting the following error when I run the pipline on one of our files.   I am using version 2.6.   It is working on most of our files but fails on this one for some reason.  Unfortunately I am not able to share the file at this time.  

    Thanks, 

    
       Michael 

Running command:
set -u pipefail; samtools view -bL /sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3/share/tbprofiler/tbdb.bed  bamDir/fileWerror.bam | samtools depth -aa --reference /sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3/share/tbprofiler/tbdb.fasta -
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3//bin/tb-profiler", line 347, in <module>
    args.func(args)
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3//bin/tb-profiler", line 93, in main_profile
    results = tbp.reformat(results,conf)
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3/lib/python3.7/site-packages/tbprofiler/reformat.py", line 247, in reformat
    results = reformat_annotations(results,conf)
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3/lib/python3.7/site-packages/tbprofiler/reformat.py", line 217, in reformat_annotations
    var["change"] = pp.reformat_mutations(var["change"],var["type"],var["locus_tag"],chr2gene_pos)
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-2.6-python3/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 53, in reformat_mutations
    gene_start = gene_info[chr_pos] + 1
KeyError: 530

**Comment by jodyphelan** [comment]
I had found some similar looking error messages and have uploaded a fix with the latest [pathogen-profiler](https://github.com/jodyphelan/pathogen-profiler) commit. Try updating this library and check if you still get the error.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

 I saw that you sent me a response to this with instructions on where to put the file but I can't seem to find it.  Could you send it again?   Thanks.

**Comment by jodyphelan** [comment]
Just sent it again.

**Comment by jodyphelan** [comment]
This issue is now fixed in the latest conda build (v2.6.1)

**Comment by harrismia** [comment]
Thanks a lot!  We will update to version 2.6.1 and let you know if we run into any issues.
