### ISSUE TITLE
-d / --dir should create the output folder

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#62]
```
% tb-profiler  profile -1 R1.fq.gz -2 R2.fq.gz -d tbp2

Using gff file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.gff
Using ref file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.fasta
Using ann file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.ann.txt
Using barcode file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.barcode.bed
Using bed file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.bed
Using json_db file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.dr.json
Using version file: /home/linuxbrew/.linuxbrew/opt/python/share/tbprofiler/tbdb.version.json
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/tb-profiler", line 433, in <module>
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/bin/tb-profiler", line 69, in main_profile
    os.mkdir(args.dir+"/"+x)
FileNotFoundError: [Errno 2] No such file or directory: 'tbp2/bam'
```

**Comment by jodyphelan** [comment]
Should be fixed now.
