### ISSUE TITLE
bedtools errors with nanopore data

### ISSUE THREAD

**Issue by nilay-p** [jodyphelan/TBProfiler#83]
Hi Jody,
I am running TBProfiler for the nanopore data of the same samples I used for illumina data. 
For some of the samples I got 2 different errors associated with database/bedtools;
1)
Running command:
set -u pipefail; bedtools coverage -b ./8644-04_nanopore.bam -a /Users/nilay/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed
Traceback (most recent call last):
  File "/Users/nilay/miniconda3/envs/tbprofiler/bin/tb-profiler", line 438, in <module>
    args.func(args)
  File "/Users/nilay/miniconda3/envs/tbprofiler/bin/tb-profiler", line 117, in main_profile
    results = tbp.reformat(results, conf, reporting_af=args.reporting_af)
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/site-packages/tbprofiler/reformat.py", line 164, in reformat
    results = add_genes(results,conf)
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/site-packages/tbprofiler/reformat.py", line 56, in add_genes
    d["gene"] = rv2gene[d["gene_id"]]
KeyError: 'Rv1631'

2) 
Running command:
set -u pipefail; bedtools coverage -b ./706-05_nanopore.bam -a /Users/nilay/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed

Error can't find nucleotide number in valS

Could you please have a look at them?
Best,
Nilay

**Comment by jodyphelan** [comment]
Hi Nilay,

I'll have a look to see if I can replicate it in any of our nanopore samples.

Jody

**Comment by jodyphelan** [comment]
Hi @nilay-p ,

I have replicated the issue (although with another gene) in some of my data. I have included a fix in the latest commit. I'll try release a conda update in the next day.

Jody
