### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nilay-p** [jodyphelan/TBProfiler#85]
Hi Jody,
I am having the following issue (the same error with both variant callers; bcftools and gatk) using TBProfiler version 2.8.3 with my illumina data.
==
Running command:
set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE\t%TBCSQ\t%TGT\t%AD]\n' ./3678-04_illumina.targets.csq.vcf.gz
Command Failed! Please Check!Exception ignored in: <generator object cmd_out at 0x10407b650>
Traceback (most recent call last):
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 162, in cmd_out
    exit(1)
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
Traceback (most recent call last):
  File "/Users/nilay/miniconda3/envs/tbprofiler/bin/tb-profiler", line 438, in <module>
    args.func(args)
  File "/Users/nilay/miniconda3/envs/tbprofiler/bin/tb-profiler", line 113, in main_profile
    run_delly = run_delly
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/site-packages/pathogenprofiler/profiler.py", line 29, in bam_profiler
    csq = csq_vcf_obj.load_csq(ann_file=conf["ann"])
  File "/Users/nilay/miniconda3/envs/tbprofiler/lib/python3.7/site-packages/pathogenprofiler/vcf.py", line 87, in load_csq
    if x[1] in gene_set or x[2] in gene_set:
IndexError: list index out of range

===
Could you please help me to fix it?

**Comment by jodyphelan** [comment]
Hi @nilay-p I think this was fixed in the latest release. Please update to v2.8.4 and try again.

**Comment by nilay-p** [comment]
It worked! Thanks @jodyphelan
